<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-sm-4">
		<h2>PROP&Oacute;SITOS</h2>
	</div>
	<div class="col-sm-4">
		<div class="form-group">
			<label for="pais">Pa&iacute;s</label>
			<select  id="filtropais" class="form-control" >
				<option value="0">-- SELECCIONAR --</option>
				<?php foreach ($this->view->pais as $pais):?>
						<option value="<?php echo($pais['ID_Pais']);?>"><?php echo($pais['Nombre_Pais']);?></option>
				<?php endforeach; ?>
			</select>
		</div>
	</div>
	<div class="col-sm-4">
		<div class="form-group">
			<label for="pais">A&ntilde;o</label>
			<select  id="filtroano" class="form-control" >
				<option value="0">-- SELECCIONAR --</option>
				<?php foreach ($this->view->ano as $ano):?>
						<option value="<?php echo($ano->id);?>"><?php echo($ano->ano);?></option>
				<?php endforeach; ?>
			</select>
		</div>
	</div>
</div>

<div class="wrapper wrapper-content">
	<div class="row">
    	<div class="ibox">
    		<div class="col-lg-12">
    			<div class="col-lg-6">
    				<strong>LISTADO DE PROPOSITOS</strong><br>
    				<div id="load">
    					<?php foreach ($this->view->proposito as $proposito):?>
        					<div class="form-group">
        						<input type="text" class="form-control" name="proposito" value="<?php echo($proposito->proposito);?>" disabled>
        						<textarea rows="3" cols="100" disabled><?php echo($proposito->descripcion);?></textarea></br>
        						<a href="#"><i class="fa fa-pencil"></i> Editar </a><a href="#"><i class="fa fa-eraser"></i> Eliminar </a><a href="#"><i class="fa fa-retweet"></i> Relacionar </a>
        					</div>	
        				<?php endforeach; ?>
    				</div>
    			</div>
    			<div class="col-lg-6">
    				<div class="ibox">
        				<div class="ibox-title">
        					<h5>A&ntilde;adir Prop&oacute;sitos</h5>
        				</div>
        				<div class="ibox-content">
							<div id="tab-1" class="">
								<div class="panel-body">
									<div class="col-lg-6">
										<div class="form-group">
											<label for="label">Prop&oacute;sito</label>
											<input type="text" class="form-control" name="proposito" id="proposito">
										</div>
										<div class="form-group">
											<label for="label">Descripci&oacute;n</label>
											<textarea id="descripcion" rows="6" cols="45">
											</textarea>
										</div>
									</div>
									<div class="col-lg-6">
										<div class="form-group">
                                			<label for="pais">Pa&iacute;s</label>
                                			<select  id="pais" class="form-control" >
                                				<option value="0">-- GLOBAL --</option>
                                				<?php foreach ($this->view->pais as $pais):?>
                                						<option value="<?php echo($pais['ID_Pais']);?>"><?php echo($pais['Nombre_Pais']);?></option>
                                				<?php endforeach; ?>
                                			</select>
                                		</div>
                                		<div class="form-group">
                                			<label for="ano">A&ntilde;o</label>
                                			<select  id="ano" class="form-control" >
                                				<option value="0">-- SELECCIONAR --</option>
                                				<?php foreach ($this->view->ano as $ano):?>
                                						<option value="<?php echo($ano->id);?>"><?php echo($ano->ano);?></option>
                                				<?php endforeach; ?>
                                			</select>
                                		</div>
                                		<button type="button" id="guardar" class="btn btn-success">Agregar</button>
									</div>
								</div>
							</div>
        				</div>
					</div>
    			</div>
    		</div>
    	</div>	
    </div>
</div>
<script type="text/javascript" src="/assets/js/jquery-confirm.js"></script>
<script type="text/javascript" src="/assets/js/proposito/proposito.js""></script>