<div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-sm-4">
                    <h2>Crear Planificaci&oacute;n</h2>
                    <ol class="breadcrumb">
                        <li>
                            <a href="/">Home</a>
                        </li>
                        <li>
                            <a href="/cplanificacion">Listado Planificaci&oacute;n</a>
                        </li>
                        <li class="active">
                            <strong>Crear Planificaci&oacute;n</strong>
                        </li>
                    </ol>
                </div>
            </div>

            <div class="wrapper wrapper-content">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="ibox">
                            <div class="ibox-title">
                            <h5>Planificaci&oacute;n</h5>
                        </div>
                    <div class="ibox-content">
                        <div class="tabs-container">
                        <ul class="nav nav-tabs">
                            <li class="active"><a data-toggle="tab" href="#tab-1">Indicadores</a></li>
                            <li class=""><a data-toggle="tab" href="#tab-2">Plazos</a></li>
                        </ul>
                        <div class="tab-content">
                            <div id="tab-1" class="tab-pane active">
                                <div class="panel-body">
                                    <div class="col-lg-6">
										<div class="form-group">
    	 									<label for="ano">A&ntilde;o</label>
        	 								<select  id="ano" class="form-control" >
        	 									<option value="0">-- SELECCIONE --</option>
                	 							<?php foreach ($this->view->ano as $ano):?>
                	 									<option value="<?php echo($ano->id);?>"><?php echo($ano->ano);?></option>
                	 							<?php endforeach; ?>
                	 						</select>
            	 						</div>
									</div>
									
									<div class="col-lg-6">
										<div class="form-group">
    	 									<label for="pais">Pa&iacute;s</label>
        	 								<select  id="pais" class="form-control" >
        	 									<option value="0">-- SELECCIONE --</option>
                	 							<?php foreach ($this->view->pais as $pais):?>
                	 									<option value="<?php echo($pais->id);?>"><?php echo($pais->pais);?></option>
                	 							<?php endforeach; ?>
                	 						</select>
            	 						</div>
									</div>
									
									<div id="loadSede">
									</div>
                                    
                                    <div class="col-lg-12">
                                        <hr>
                                        <h2>Elija los Indicadores para el a&ntilde;o</h2>
                                        <table id="example" class="display" style="width:100%">
                                            <thead>
                                                <tr>
                                                    <th></th>
                                                    <th>Indicador</th>
                                                    <th>Tipo</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td></td>
                                                    <td>PAA - País Auditado Anualmenten</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PLDV - Promedio Libre Disposición Vivienda</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>%FR - Porcentaje de Fondos Restringidos</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PLDV - Promedio Libre Disposición Vivienda</td>
                                                    <td>DFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>%FR - Porcentaje de Fondos Restringidos</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PAA - País Auditado Anualmenten</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PLDV - Promedio Libre Disposición Vivienda</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>%FR - Porcentaje de Fondos Restringidos</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PLDV - Promedio Libre Disposición Vivienda</td>
                                                    <td>DFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>%FR - Porcentaje de Fondos Restringidos</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PAA - País Auditado Anualmenten</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PLDV - Promedio Libre Disposición Vivienda</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>%FR - Porcentaje de Fondos Restringidos</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PLDV - Promedio Libre Disposición Vivienda</td>
                                                    <td>DFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>%FR - Porcentaje de Fondos Restringidos</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PAA - País Auditado Anualmenten</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PLDV - Promedio Libre Disposición Vivienda</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>%FR - Porcentaje de Fondos Restringidos</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PLDV - Promedio Libre Disposición Vivienda</td>
                                                    <td>DFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>%FR - Porcentaje de Fondos Restringidos</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PAA - País Auditado Anualmenten</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PLDV - Promedio Libre Disposición Vivienda</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>%FR - Porcentaje de Fondos Restringidos</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PLDV - Promedio Libre Disposición Vivienda</td>
                                                    <td>DFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>%FR - Porcentaje de Fondos Restringidos</td>
                                                    <td>AFF</td>
                                                </tr>
                                                
                                            </tbody>
                                            <tfoot>
                                            </tfoot>
                                        </table>
                                    </div>
                            

                                </div>
                            </div>
                            <div id="tab-2" class="tab-pane">
                                <div class="panel-body">
                                    <div class="col-lg-12">
                                        <div class="table-responsive">
                                            <table class="table table-striped table-hover dataTables-example" >
                                            <thead>
                                            <tr>
                                                <th>Meses</th>
                                                <th>Plan</th>
                                                <th>Real</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <tr class="gradeX">
                                                <td>Enero</td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                            </tr>
                                            <tr class="gradeC">
                                                <td>Febrero</td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                            </tr>
                                            <tr class="gradeA">
                                                <td>Marzo</td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                            </tr>
                                            <tr class="gradeA">
                                                <td>Abril</td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                            </tr>
                                            <tr class="gradeA">
                                                <td>Mayo</td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                            </tr>
                                            <tr class="gradeA">
                                                <td>Junio</td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                            </tr>
                                            <tr class="gradeA">
                                                <td>Julio</td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                            </tr>
                                            <tr class="gradeA">
                                                <td>Agosto</td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                            </tr>
                                            <tr class="gradeA">
                                                <td>Septiembre</td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                            </tr>
                                            <tr class="gradeA">
                                                <td>Octubre</td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                            </tr>
                                            <tr class="gradeA">
                                                <td>Novimbre</td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                            </tr>
                                            <tr class="gradeA">
                                                <td>Deciembre</td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                            </tr>
                                            </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>

                        </div>
                    </div>
                    <div class="actions clearfix paddingTop-20">
                        <button type="button" id="guardar-planificacion" class="btn btn-success btn-lg pull-right btn-salvar">Guardar</button>
							<a href="/cplanificacion" class="btn btn-danger btn-lg pull-right">Cancelar</a>
                    </div>

                        </div>
                        </div>  
                </div>
                </div>
            </div>

<script>
         $(document).ready(function(){
            $('.chosen-select').chosen({width: "100%"});
             $(".select2_demo_2").select2();

            //Checkbox KPIS
             $('#example').DataTable( {
            	 "language": {
                     "url": "https://cdn.datatables.net/plug-ins/1.10.15/i18n/Spanish.json"
                 },
                columnDefs: [ {
                    className: 'select-checkbox',
                    targets:   0
                } ],
                select: {
                    style:    'os',
                    selector: 'td:first-child'
                },
                order: [[ 1, 'asc' ]]
            } );

            $('#example2').DataTable( {
           	 "language": {
                 "url": "https://cdn.datatables.net/plug-ins/1.10.15/i18n/Spanish.json"
             },
                columnDefs: [ {
                    className: 'select-checkbox',
                    targets:   0
                } ],
                select: {
                    style:    'os',
                    selector: 'td:first-child'
                },
                order: [[ 1, 'asc' ]]
            } );
        });

    </script>
    <script type="text/javascript" src="/assets/js/cplanificacion/cplanificacion.js""></script>
    <script type="text/javascript" src="/assets/js/jquery-confirm.js"></script>
   