<div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-sm-4">
                    <h2>Nova Meta</h2>
                    <ol class="breadcrumb">
                        <li>
                            <a href="/">Dashboard</a>
                        </li>
                        <li>
                            <a href="/produtos.php">Metas</a>
                        </li>
                        <li class="active">
                            <strong>Nova Metas</strong>
                        </li>
                    </ol>
                </div>
            </div>

            <div class="wrapper wrapper-content">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="ibox">
                            <div class="ibox-title">
                            <h5>Nova Meta</h5>
                        </div>
                    <div class="ibox-content">
                        <div class="tabs-container">
                        <ul class="nav nav-tabs">
                            <li class="active"><a data-toggle="tab" href="#tab-1"> KPI's</a></li>
                            <li class=""><a data-toggle="tab" href="#tab-2">Prazos</a></li>
                            <li class=""><a data-toggle="tab" href="#tab-3">Indice de Excelencia</a></li>
                        </ul>
                        <div class="tab-content">
                            <div id="tab-1" class="tab-pane active">
                                <div class="panel-body">
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                        <label for="label">Ano</label>
                                        <input type="text" class="form-control" name="ano">
                                        </div>
                                    </div>
                                    
                                    <div class="col-lg-12">
                                        <hr>
                                        <h2>Escolha os KPI's para o ano</h2>
                                        <table id="example" class="display" style="width:100%">
                                            <thead>
                                                <tr>
                                                    <th></th>
                                                    <th>Indicador</th>
                                                    <th>Tipo</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td></td>
                                                    <td>PAA - País Auditado Anualmenten</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PLDV - Promedio Libre Disposición Vivienda</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>%FR - Porcentaje de Fondos Restringidos</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PLDV - Promedio Libre Disposición Vivienda</td>
                                                    <td>DFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>%FR - Porcentaje de Fondos Restringidos</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PAA - País Auditado Anualmenten</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PLDV - Promedio Libre Disposición Vivienda</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>%FR - Porcentaje de Fondos Restringidos</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PLDV - Promedio Libre Disposición Vivienda</td>
                                                    <td>DFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>%FR - Porcentaje de Fondos Restringidos</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PAA - País Auditado Anualmenten</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PLDV - Promedio Libre Disposición Vivienda</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>%FR - Porcentaje de Fondos Restringidos</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PLDV - Promedio Libre Disposición Vivienda</td>
                                                    <td>DFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>%FR - Porcentaje de Fondos Restringidos</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PAA - País Auditado Anualmenten</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PLDV - Promedio Libre Disposición Vivienda</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>%FR - Porcentaje de Fondos Restringidos</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PLDV - Promedio Libre Disposición Vivienda</td>
                                                    <td>DFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>%FR - Porcentaje de Fondos Restringidos</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PAA - País Auditado Anualmenten</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PLDV - Promedio Libre Disposición Vivienda</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>%FR - Porcentaje de Fondos Restringidos</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PLDV - Promedio Libre Disposición Vivienda</td>
                                                    <td>DFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>%FR - Porcentaje de Fondos Restringidos</td>
                                                    <td>AFF</td>
                                                </tr>
                                                
                                            </tbody>
                                            <tfoot>
                                            </tfoot>
                                        </table>
                                    </div>
                            

                                </div>
                            </div>
                            <div id="tab-2" class="tab-pane">
                                <div class="panel-body">
                                    <div class="col-lg-12">
                                        <div class="table-responsive">
                                            <table class="table table-striped table-hover dataTables-example" >
                                            <thead>
                                            <tr>
                                                <th>Meses</th>
                                                <th>Plan</th>
                                                <th>Real</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <tr class="gradeX">
                                                <td>Janeiro</td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                            </tr>
                                            <tr class="gradeC">
                                                <td>Fevereiro</td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                            </tr>
                                            <tr class="gradeA">
                                                <td>Março</td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                            </tr>
                                            <tr class="gradeA">
                                                <td>Abril</td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                            </tr>
                                            <tr class="gradeA">
                                                <td>Maio</td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                            </tr>
                                            <tr class="gradeA">
                                                <td>Junho</td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                            </tr>
                                            <tr class="gradeA">
                                                <td>Julho</td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                            </tr>
                                            <tr class="gradeA">
                                                <td>Agosto</td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                            </tr>
                                            <tr class="gradeA">
                                                <td>Setembro</td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                            </tr>
                                            <tr class="gradeA">
                                                <td>Outubro</td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                            </tr>
                                            <tr class="gradeA">
                                                <td>Novembro</td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                            </tr>
                                            <tr class="gradeA">
                                                <td>Dezembro</td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                                <td>
                                                    <select class="form-control" name="status">
                                                        <option>En edición</option>
                                                        <option>Cerrado</option>
                                                    </select>
                                                </td>
                                            </tr>
                                            </tbody>
                                            <tfoot>
                                            <tr>
                                                <th>Meses</th>
                                                <th>Plan</th>
                                                <th>Real</th>
                                            </tr>
                                            </tfoot>
                                            </table>
                                        </div>
                                    </div>
                                </div>

                        </div>
                            <div id="tab-3" class="tab-pane">
                                <div class="panel-body">
                                    <div class="col-lg-12">
                                        <div class="col-lg-12">
                                        <hr>
                                        <h2>Escolha os Indices de Excelencia para o ano</h2>
                                        <table id="example2" class="display" style="width:100%">
                                            <thead>
                                                <tr>
                                                    <th></th>
                                                    <th>Indicador</th>
                                                    <th>Tipo</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td></td>
                                                    <td>PAA - País Auditado Anualmenten</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PLDV - Promedio Libre Disposición Vivienda</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>%FR - Porcentaje de Fondos Restringidos</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PLDV - Promedio Libre Disposición Vivienda</td>
                                                    <td>DFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>%FR - Porcentaje de Fondos Restringidos</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PAA - País Auditado Anualmenten</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PLDV - Promedio Libre Disposición Vivienda</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>%FR - Porcentaje de Fondos Restringidos</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PLDV - Promedio Libre Disposición Vivienda</td>
                                                    <td>DFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>%FR - Porcentaje de Fondos Restringidos</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PAA - País Auditado Anualmenten</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PLDV - Promedio Libre Disposición Vivienda</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>%FR - Porcentaje de Fondos Restringidos</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PLDV - Promedio Libre Disposición Vivienda</td>
                                                    <td>DFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>%FR - Porcentaje de Fondos Restringidos</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PAA - País Auditado Anualmenten</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PLDV - Promedio Libre Disposición Vivienda</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>%FR - Porcentaje de Fondos Restringidos</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PLDV - Promedio Libre Disposición Vivienda</td>
                                                    <td>DFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>%FR - Porcentaje de Fondos Restringidos</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PAA - País Auditado Anualmenten</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PLDV - Promedio Libre Disposición Vivienda</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>%FR - Porcentaje de Fondos Restringidos</td>
                                                    <td>AFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>PLDV - Promedio Libre Disposición Vivienda</td>
                                                    <td>DFF</td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>%FR - Porcentaje de Fondos Restringidos</td>
                                                    <td>AFF</td>
                                                </tr>
                                                
                                            </tbody>
                                            <tfoot>
                                            </tfoot>
                                        </table>
                                    </div> 
                                    </div>
                                </div>
                            </div>

                    </div>
                    <div class="actions clearfix paddingTop-20">
<button type="button" class="btn btn-success btn-lg pull-right btn-salvar"><i class="fa fa-plus"></i> Salvar</button>
<button type="button" class="btn btn-danger btn-lg pull-right"><i class="fa fa-trash"></i> Cancelar</button>
                    </div>

                        </div>
                        </div>  
                </div>
                </div>
            </div>

<script>
         $(document).ready(function(){
            $('.chosen-select').chosen({width: "100%"});
             $(".select2_demo_2").select2();

            //Checkbox KPIS
             $('#example').DataTable( {
            	 "language": {
                     "url": "https://cdn.datatables.net/plug-ins/1.10.15/i18n/Spanish.json"
                 },
                columnDefs: [ {
                    className: 'select-checkbox',
                    targets:   0
                } ],
                select: {
                    style:    'os',
                    selector: 'td:first-child'
                },
                order: [[ 1, 'asc' ]]
            } );

            $('#example2').DataTable( {
           	 "language": {
                 "url": "https://cdn.datatables.net/plug-ins/1.10.15/i18n/Spanish.json"
             },
                columnDefs: [ {
                    className: 'select-checkbox',
                    targets:   0
                } ],
                select: {
                    style:    'os',
                    selector: 'td:first-child'
                },
                order: [[ 1, 'asc' ]]
            } );

                $('.dataTables-example').dataTable({
                pageLength: 25,
                responsive: true,
                dom: '<"html5buttons"B>lTfgitp',

            });
        });

    </script>