<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-sm-4">
		<h2>Crear Planificaci&oacute;n</h2>
		 <ol class="breadcrumb">
		 	<li>
                <a href="/">Home</a>
            </li>
            <li class="active">
                <strong>Crear Planificaci&oacute;n</strong>
            </li>
		 </ol>
	</div>
	<div class="col-sm-8">
		<div class="title-action">
			<a href="/cplanificacion/add" class="btn  btn-success btn-lg">Crear Planificaci&oacute;n</a>
		</div>
	</div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox float-e-margins">
				<div class="ibox-title">
					<h5>Listado de Planificaci&oacute;n</h5>
				</div>
				<div class="ibox-content">
					<table class="table table-striped table-bordered table-hover dataTables-example" >
						<thead>
                    		<tr>
                                <th>A&ntilde;o</th>
                                <th>Status</th>
                                <th>Opções</th>
                    		</tr>
                    	</thead>
                    	<tbody>
                    	<?php foreach ($this->view->cplanificacion as $cplanificacion): ?>
                    		<tr class="gradeX">
                    		<td><?php echo($cplanificacion->ano);?></td>
                    		<td><?php ($cplanificacion->situation == '1' ? $cplanificacion->situation = 'Activo' : $cplanificacion->situation = 'Inactivo'); echo($cplanificacion->situation);?></td>
                    		<td class="center"><a href="/cplanificacion/show/<?php echo($cplanificacion->id);?>" class="btn btn-success btn-xs"><i class="fa fa-paste"></i> Editar</a><a href="/cplanificacion/duplicar/<?php echo($cplanificacion->id);?>" class="btn btn-warning btn-xs"><i class="fa fa-paste"></i> Duplicar</a><a href="/cplanificacion/delete/<?php echo($cplanificacion->id);?>" class="btn btn-info btn-xs"><i class="fa fa-trash"></i> Deletar</a></td>
                    	<?php endforeach; ?>
                    	</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>