<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-sm-4">
		<h2>Editar A&ntilde;o</h2>
		<ol class="breadcrumb">
			<li>
				<a href="/">Home</a>
			</li>
			<li>
				<a href="/anos">A&ntilde;os</a>
			</li>
			<li class="active">
				<strong>Editar A&ntilde;o</strong>
			</li>
		</ol>
	</div>
</div>

<div class="wrapper wrapper-content">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox">
				<div class="ibox-title">
					<h5>Editar A&ntilde;O</h5>
				</div>
				<div class="ibox-content">
					<div class="tabs-container">
						<ul class="nav nav-tabs">
							<li class="active"><a data-toggle="tab" href="#tab-1"></a></li>
						</ul>
						<div class="tab-content">
							<div id="tab-1" class="tab-pane active">
								<div class="panel-body">
									<div class="col-lg-6">
										<div class="form-group">
											<label for="label">A&ntilde;o</label>
											<input type="text" class="form-control" name="ano" id="ano" value="<?php echo($this->view->ano->ano);?>">
										</div>
										<div class="form-group">
										<?php 
										    if($this->view->ano->situation == 0)
                                            {
                                                $selecionar = 'selected';
                                            }
                                            
                                            if($this->view->ano->situation == 1)
                                            {
                                                $activo = 'selected';
                                            }
                                            
                                            if($this->view->ano->situation == 2)
                                            {
                                                $inactivo = 'selected';
                                            }
                                        ?>
											<label for="label">Status</label>
											<select class="form-control" name="status" id="status">
												<option <?php echo ($selecionar);?> value="0" >-- SELECCIONE --</option>
                                                <option <?php echo ($activo);?> value="1">Activo</option>
                                                <option <?php echo ($inactivo);?> value="2">Inactivo</option>
											</select>
										</div>
										<div class="form-group">
											<input type="hidden" class="form-control" id="id" value="<?php echo($this->view->ano->id);?>">
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="actions clearfix paddingTop-20">
							<button type="button" id="actualizar-ano" class="btn btn-success btn-lg pull-right btn-salvar">Guardar</button>
							<a href="/anos" class="btn btn-danger btn-lg pull-right">Cancelar</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript" src="/assets/js/ano/ano.js""></script>
<script type="text/javascript" src="/assets/js/jquery-confirm.js"></script>
<script>
	$("#actualizar-ano").click(function() {
		ActualizarAno();
	});
</script>