<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-sm-4">
		<h2>A&ntilde;os</h2>
		 <ol class="breadcrumb">
		 	<li>
                <a href="/">Home</a>
            </li>
            <li class="active">
                <strong>A&ntilde;os</strong>
            </li>
		 </ol>
	</div>
	<div class="col-sm-8">
		<div class="title-action">
			<a href="/anos/add" class="btn  btn-success btn-lg">Agregar A&ntilde;o</a>
		</div>
	</div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox float-e-margins">
				<div class="ibox-title">
					<h5>Listado de A&ntilde;os</h5>
				</div>
				<div class="ibox-content">
					<table class="table table-striped table-bordered table-hover dataTables-example" >
						<thead>
                    		<tr>
                                <th>ID</th>
                                <th>A&ntilde;o</th>
                                <th>Status</th>
                                <th>Opções</th>
                    		</tr>
                    	</thead>
                    	<tbody>
                    	<?php foreach ($this->view->ano as $ano): ?>
                    		<tr class="gradeX">
                    		<td><?php echo($ano->id);?></td>
                    		<td><?php echo($ano->ano);?></td>
                    		<td>Ativo</td>
                    		<td class="center"><a href="#" class="btn btn-success btn-xs"><i class="fa fa-paste"></i> Editar</a><a href="#" class="btn btn-warning btn-xs"><i class="fa fa-paste"></i> Duplicar</a><a href="#" class="btn btn-info btn-xs"><i class="fa fa-trash"></i> Deletar</a></td>
                    	<?php endforeach; ?>
                    	</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>