<div class="container">
	<div class="row">
		<h1 class="h1">
			<?php $this->getPageTitle();?>
			<hr align="left" noshade="noshade" size="2" width="80%" />
		</h1>
	</div>
	 <?php foreach ($this->view->ano as $ano): ?>
 	<div class="row">
 		<p class="text-justify"><?php echo('Id: '. $ano->id);?></p>
 		<p class="text-justify"><?php echo('A&ntilde;o: '. $ano->ano);?></p>
 		<hr align="left" noshade="noshade" size="2" width="80%" />
 	</div>
 	<?php endforeach; ?>
 	<a type="button" href="/anos/add/"</a> A&ntilde;adir A&ntilde;o
</div>