<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-sm-4">
		<h2>A&ntilde;o</h2>
		 <ol class="breadcrumb">
		 	<li>
                <a href="/">Home</a>
            </li>
            <li class="active">
                <strong>A&ntilde;o</strong>
            </li>
		 </ol>
	</div>
	<div class="col-sm-8">
		<div class="title-action">
			<a href="/anos/add" class="btn  btn-success btn-lg">Agregar A&ntilde;o</a>
		</div>
	</div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox float-e-margins">
				<div class="ibox-title">
					<h5>Listado de A&ntilde;o</h5>
				</div>
				<div class="ibox-content">
					<table class="table table-striped table-bordered table-hover dataTables-example" >
						<thead>
                    		<tr>
                                <th>A&ntilde;o</th>
                                <th>Status</th>
                                <th>Opciones</th>
                    		</tr>
                    	</thead>
                    	<tbody>
                    	<?php foreach ($this->view->ano as $ano): ?>
                    		<tr class="gradeX">
                    		<td><?php echo($ano->ano);?></td>
                    		<td><?php ($ano->situation == '1' ? $ano->situation = 'Activo' : $ano->situation = 'Inactivo'); echo($ano->situation);?></td>
                    		<td class="center"><a href="/anos/show/<?php echo($ano->id);?>" class="btn btn-success btn-xs"><i class="fa fa-paste"></i> Editar</a><a href="#" onclick="Delete(<?php echo($ano->id);?>);" class="btn btn-info btn-xs"><i class="fa fa-trash"></i> Deletar</a></td>
                    	<?php endforeach; ?>
                    	</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript" src="/assets/js/jquery-confirm.js"></script>
<script>
$(document).ready(function(){
    $('.dataTables-example').dataTable({
   	 "language": {
         "url": "https://cdn.datatables.net/plug-ins/1.10.15/i18n/Spanish.json"
     },
        pageLength: 25,
        responsive: true,
        dom: '<"html5buttons"B>lTfgitp',
        buttons: [
            { extend: 'copy'},
            {extend: 'excel', title: 'ExampleFile'},
            {extend: 'pdf', title: 'ExampleFile'},

            {extend: 'print',
             customize: function (win){
                    $(win.document.body).addClass('white-bg');
                    $(win.document.body).css('font-size', '10px');

                    $(win.document.body).find('table')
                            .addClass('compact')
                            .css('font-size', 'inherit');
            }
            }
        ]

    });

});

function Delete(id)
{
	var id = id
    $.confirm({
        content: 'Est\u00E1 seguro de que desea borrar esta a\u00F1o',
        buttons: {
            specialKey: {
                text: 'S\u00ED',
                action: function(){
                	window.location.replace("/anos/delete/"+id);
                }
            },
            alphabet: {
                text: 'No',
                action: function(){
                    return;
                }
            }
        }
    });
}

</script>