<div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-sm-4">
                    <h2>Generador de Informes</h2>
                    <ol class="breadcrumb">
                        <li>
                            <a href="/">Home</a>
                        </li>
                        <li class="active">
                            <strong>Generador de Informes</strong>
                        </li>
                    </ol>
                </div>
            </div>

            <div class="wrapper wrapper-content">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="ibox">
                            <div class="ibox-title">
                            <h5>Generador de Informes</h5>
                        </div>
                    <div class="ibox-content">
                        <div class="tabs-container">
                        <ul class="nav nav-tabs">
                            <li class="active"><a data-toggle="tab" href="#tab-1">Configuraci&oacute;n</a></li>
                            <li class=""><a data-toggle="tab" href="#tab-2">Resultado Gr&aacute;fico</a></li>
                        </ul>
                        <div class="tab-content">
                            <div id="tab-1" class="tab-pane active">
                                <div class="panel-body">
                                <div class="col-lg-12">
										<div class="form-group" id="pais">
    	 									<label for="tipo">Generar Informe por</label><br>
        									<div class="form-group" id="pais">
                                                 <input id="c1" type="checkbox" value="pais" class="js-switch"/>
                                                 <label for="pais">Pa&iacute;s</label><br>
                	 						</div>
                	 						<div class="form-group" id="sede">
                                                 <input id="c2" type="checkbox" value="sede" class="js-switch_2"/>
                                                 <label for="sede">Sede</label><br>
                	 						</div>
            	 						</div>
									</div>
									
									 <div class="col-lg-6">
										<div class="form-group">
    	 									<label for="ano">A&ntilde;o</label>
        	 								<select  id="ano" class="form-control" >
        	 									<option value="0">-- SELECCIONE --</option>
                	 							<?php foreach ($this->view->ano as $ano):?>
                	 									<option value="<?php echo($ano->id);?>"><?php echo($ano->ano);?></option>
                	 							<?php endforeach; ?>
                	 						</select>
            	 						</div>
									</div>
									
									<div id="Listpaises"></div>
									<div id="Listindicadores"></div>
                                </div>
                                
                            </div>
                            <div id="tab-2" class="tab-pane">
                                <div class="panel-body">
                                    <div class="col-lg-12">
                                        <div class="table-responsive">
                                            <div id="container" style="width: 60%; margin: 0 auto; width: 60%;">
                                            	<canvas id="canvas">
                                            		
                                            	</canvas>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                        </div>
                    </div>
                    <div class="actions clearfix paddingTop-20">
                        <button type="button" id="generar-resultado" class="btn btn-success btn-lg pull-right btn-salvar">Generar</button>
						<a href="/" class="btn btn-danger btn-lg pull-right">Cancelar</a>
                    </div>

                        </div>
                        <div id="loading-techo">
                        	<div class="loading"><img src="/loading.gif"></div>
                        </div>
                        </div>  
                </div>
                </div>
            </div>

<script>
         $(document).ready(function(){
        	 var elem = document.querySelector('.js-switch');
        	 var switchery = new Switchery(elem, { color: '#1AB394' });

        	 var elem_2 = document.querySelector('.js-switch_2');
        	 var switchery_2 = new Switchery(elem_2, { color: '#ED5565' });

        	 $('#loading-techo').hide();

        	 $("#generar-resultado").click(function() {
        		 GeneraResultado(table.rows('.selected').data(), table1.rows('.selected').data());
            	});
        });

    </script>
    <script type="text/javascript" src="/assets/js/generador/generador.js""></script>
    <script type="text/javascript" src="/assets/js/jquery-confirm.js"></script>
    <script src="/assets/js/plugins/switchery/switchery.js"></script>
    <link href="/assets/css/plugins/switchery/switchery.css" rel="stylesheet">
    