<head>
	<title>Informe Mensual</title>
	<script src="/assets/js/Chart.bundle.js"></script>
	<script src="/assets/js/utils.js"></script>
	<style>
	canvas {
		-moz-user-select: none;
		-webkit-user-select: none;
		-ms-user-select: none;
	}
	</style>
</head>
<div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-sm-4">
                    <h2>Generador de Informes</h2>
                    <ol class="breadcrumb">
                        <li>
                            <a href="/">Home</a>
                        </li>
                        <li class="active">
                            <strong>Generador de Informes</strong>
                        </li>
                    </ol>
                </div>
            </div>

            <div class="wrapper wrapper-content">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="ibox">
                            <div class="ibox-title">
                            <h5>Generador de Informes</h5>
                        </div>
                    <div class="ibox-content">
                        <div class="tabs-container">
                        <ul class="nav nav-tabs">
                            <li class="active"><a data-toggle="tab" href="#tab-1">Configuraci&oacute;n</a></li>
                        </ul>
                        <div class="tab-content">
                            <div id="tab-1" class="tab-pane active">
                                <div class="panel-body">
                                    <div class="col-lg-3">
                                    		<div class="form-group">
        	 									<label for="tipo">Generar Informe por</label><br>
        	 									<div class="i-checks">
        	 										<label> <input type="radio" id="paises "value="paises" name="tipo"> <i></i>Paises</label>
        	 									</div>
                	 						</div>
                	 						<div class="form-group">
        	 									<div class="i-checks"><label> <input type="radio" id="sedes" value="sedes" name="tipo"> <i></i>Sedes</label></div>
                	 						</div>
    								</div>
									<div class="col-lg-3">
										<div class="form-group">
    	 									<label for="ano">A&ntilde;o</label>
        	 								<select  id="ano" class="form-control" >
        	 									<option value="0">-- SELECCIONE --</option>
                	 							<?php foreach ($this->view->ano as $ano):?>
                	 									<option value="<?php echo($ano->id);?>"><?php echo($ano->ano);?></option>
                	 							<?php endforeach; ?>
                	 						</select>
            	 						</div>
                                	</div>
                                    <div class="col-lg-3">
                                    	<div id="Listpaises"></div>
                                    </div>
                                    <div class="col-lg-12">
                                    <div id="ListIndicador"></div>
                                    </div>
                                    
                                 </div>
                            </div>
                      </div>      
                            <div id="tab-2" class="tab-pane">
                                <div class="panel-body">
                                    <div class="col-lg-12">
                                        <div class="table-responsive">
                                            <div id="container" style="width: 60%; margin: 0 auto; width: 60%;">
                                            	<canvas id="canvas">
                                            		
                                            	</canvas>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                        </div>
                    </div>
                    <div class="actions clearfix paddingTop-20">
                        <button type="button" id="generar-resultado" class="btn btn-success btn-lg pull-right btn-salvar">Generar</button>
						<a href="/" class="btn btn-danger btn-lg pull-right">Cancelar</a>
                    </div>

                        </div>
                        </div>  
                </div>
                </div>
            </div>
<link href="assets/css/plugins/iCheck/custom.css" rel="stylesheet">            
<script src="assets/js/plugins/iCheck/icheck.min.js"></script>
<script>
$(document).ready(function () {
	//Check de Pais e Sede
    $('.i-checks').iCheck({
        checkboxClass: 'icheckbox_square-green',
        radioClass: 'iradio_square-green',
    });

    var config = {
            '.chosen-select'           : {},
            '.chosen-select-deselect'  : {allow_single_deselect:true},
            '.chosen-select-no-single' : {disable_search_threshold:10},
            '.chosen-select-no-results': {no_results_text:'Oops, nothing found!'},
            '.chosen-select-width'     : {width:"95%"}
            }
        for (var selector in config) {
            $(selector).chosen(config[selector]);
        }
});        

$("#generar-resultado").click(function() {
	 GeneraResultado();
	});
</script>
<script type="text/javascript" src="/assets/js/generador/generador.js""></script>
<script type="text/javascript" src="/assets/js/jquery-confirm.js"></script>
    