<html>
	<head>
		<title>Monitoreo de Proyecto por Pa&iacute;s</title>
		<script src="/assets/js/Chart.bundle.js"></script>
		<script src="/assets/js/utils.js"></script>
		<style>
            canvas 
            {
        		-moz-user-select: none;
        		-webkit-user-select: none;
        		-ms-user-select: none;
            }
        </style>
	</head>
	<body>
		<div class="panel-body">
			<div class="col-lg-3">
				<div class="form-group">
					<label for="ano">A&ntilde;o</label>
					<select  id="ano" class="form-control" >
						<option value="0">-- SELECCIONE --</option>
						<?php foreach ($this->view->ano as $ano):?>
    					<option value="<?php echo($ano->id);?>"><?php echo($ano->ano);?></option>
    					<?php endforeach; ?>
					</select>
				</div>
			</div>
			<div id="loadPais"></div>
		</div>
		<div id="dados" type="hidden"></div>
        <div id="loading-techo">
        	<div class="loading"><img src="/loading.gif"></div>
        </div>
	</body>
	<script type="text/javascript" src="/assets/js/tinformes/mproyecto.js"></script>
	<script>
    $(document).ready(function() 
   	{
    	$('#loading-techo').hide();

    });
</script>
</html>