<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-sm-4">
		<h2>A&ntilde;adir Proyecto</h2>
		<ol class="breadcrumb">
			<li>
				<a href="/">Home</a>
			</li>
			<li class="active">
				<strong>A&ntilde;adir Proyecto</strong>
			</li>
		</ol>
	</div>
</div>

<div class="wrapper wrapper-content">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox">
				<div class="ibox-title">
					<h5>A&ntilde;adir Proyecto</h5>
				</div>
				<div class="ibox-content">
					<div class="tabs-container">
						<ul class="nav nav-tabs">
							<li class="active"><a data-toggle="tab" href="#tab-1"></a></li>
						</ul>
						<div class="tab-content">
							<div id="tab-1" class="tab-pane active">
								<div class="panel-body">
									<div class="col-lg-6">
            	 						<div class="form-group">
											<label for="label">Nombre Proyecto</label>
											<input type="text" class="form-control" name="nombre" id="nombre">
										</div>
									</div>
									<div class="col-lg-6">
            	 						<div class="form-group">
											<label for="label">Responsable</label>
											<input type="text" class="form-control" name="responsable" id="responsable">
										</div>
									</div>
									
									<div class="col-lg-12">
                                        <hr>
                                        <h2>Cada proyecto puede tener un m&aacute;ximo de 10 KPIs (mientras menos, mejor)</h2>
                                        <table id="example" class="display" style="width:100%">
                                            <thead>
                                                <tr>
                                                    <th></th>
                                                    <th hidden></th>
                                                    <th>Indicador</th>
                                                    <th>Temporalidad</th>
                                                    <th>Tipo</th>
                                                    <th>Ponderacion</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <?php foreach ($this->view->indicador as $indicador): ?>
                        							<tr>
                                            		<td></td>
                                            		<td hidden><?php echo($indicador->id);?></td>
                                            		<td><?php echo($indicador->indicador);?></td>
                                            		<td><?php echo($indicador->temporalidad);?></td>
                                            		<td><?php echo($indicador->tipo);?></td>
                                            		<td><input type="ponderacion" name="ponderacion" id="<?php echo($indicador->id);?>"></td>
                                            		</tr>
                                            	<?php endforeach; ?>
                                            </tbody>
                                            <tfoot>
                                            </tfoot>
                                        </table>
                                    </div>
                                    
                                    <div class="form-group">
                    			<input type="hidden" class="form-control" id="idplanificacion" value="<?php echo($_GET['id']);?>">
                    		</div>
								</div>
							</div>
						</div>
						<div class="actions clearfix paddingTop-20">
							<button type="button" id="guardar-proyecto" class="btn btn-success btn-lg pull-right btn-salvar">Guardar</button>
							<a href="/planificacion" class="btn btn-danger btn-lg pull-right">Cancelar</a>
						</div>
					</div>
					<div id="loading-techo">
                    	<div class="loading"><img src="/loading.gif"></div>
                    </div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript" src="/assets/js/proyecto/proyecto.js""></script>
<script type="text/javascript" src="/assets/js/jquery-confirm.js"></script>
<script>
 $(document).ready(function(){
	 $('#loading-techo').hide();

     //Indicadores
     $('#example').DataTable( {
    	 "language": {
             "url": "https://cdn.datatables.net/plug-ins/1.10.15/i18n/Spanish.json"
         },
        columnDefs: [ {
            className: 'select-checkbox',
            targets:   0, 
            checkboxes: {selectRow: true}
        } ],
        select: {
            style:    'multi',
            selector: 'td:first-child'
        },
        order: [[ 1, 'asc' ]]
    } );

     var table = $('#example').DataTable();

     $('#example tbody').on( 'click', 'td:first-child', function () {
         var kpi = $(this).toggleClass('selected');
     } );

     $("#guardar-proyecto").click(function() {
         
        $(table.rows('.selected').data()).each(function(index) 
		{
        	var valor = 0;
        	valor = SetaPonderacion(this[1])
        	this[6] = valor;
        	this[7] = $('#idplanificacion').val();
		});

    	 GuardarProyecto(table.rows('.selected').data());
  	});
     
});

 function SetaPonderacion(id)
 {		
	 var dados = [""];

	 dados['indicador'] = id;
	 dados['valor'] = $('#'+id).val();
	 
	 return dados['valor'];
 }

</script>