<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-sm-4">
		<h2>A&ntilde;adir Tipo</h2>
		<ol class="breadcrumb">
			<li>
				<a href="/">Home</a>
			</li>
			<li>
				<a href="/tipos">Tipo</a>
			</li>
			<li class="active">
				<strong>A&ntilde;adir Tipo</strong>
			</li>
		</ol>
	</div>
</div>

<div class="wrapper wrapper-content">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox">
				<div class="ibox-title">
					<h5>A&ntilde;adir Tipo</h5>
				</div>
				<div class="ibox-content">
					<div class="tabs-container">
						<ul class="nav nav-tabs">
							<li class="active"><a data-toggle="tab" href="#tab-1"></a></li>
						</ul>
						<div class="tab-content">
							<div id="tab-1" class="tab-pane active">
								<div class="panel-body">
									<div class="col-lg-6">
										<div class="form-group">
											<label for="label">Tipo</label>
											<input type="text" class="form-control" name="tipo" id="tipo">
										</div>
										<div class="form-group">
											<label for="label">Status</label>
											<select class="form-control" name="status" id="status">
												<option value="0">-- SELECCIONE --</option>
                                                <option value="1">Activo</option>
                                                <option value="2">Inactivo</option>
											</select>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="actions clearfix paddingTop-20">
							<button type="button" id="guardar-tipo" class="btn btn-success btn-lg pull-right btn-salvar">Guardar</button>
							<a href="/tipos" class="btn btn-danger btn-lg pull-right">Cancelar</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript" src="/assets/js/tipo/tipo.js""></script>
<script type="text/javascript" src="/assets/js/jquery-confirm.js"></script>
<script>
	$("#guardar-tipo").click(function() {
		GuardarTipo();
	});
</script>