<div id="wrapper">
            <div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-sm-4">
               <?php 
                    if($_SERVER['SERVER_NAME'] == 'admin.planificacion.techo.org' || $_SERVER['SERVER_NAME'] == 'localhost')
                    {
                        $title= '<h2>Admin Planificaci&oacute;n</h2>';
                    }
                    else
                    {
                        $title = '<h2>Sistema de Planificaci&oacute;n</h2>';
                    }
                    echo($title);
                ?>
                    <ol class="breadcrumb">
                        <li>
                            <a href="/">est&aacute;s aqu&iacute;</a>
                        </li>
                        <li class="active">
                            <strong>Home</strong>
                        </li>
                    </ol>
                </div>
            </div>
            <div class="wrapper wrapper-content">
                <div class="big-box animated fadeInRightBig">
                 <!--  <h3 class="font-bold">Sistema de Planificaci&oacute;n</h3>  -->  
                    <div class="error-desc">
                        <?php 
                  /*      session_start(); 
                        echo('<pre>');
                        echo(print_r($_SESSION, true))
                   */     
                        ?>
                    </div>
                </div>
            </div>
</div>