<div class="container">
    <div class="row"></div>
    <div class="row">
        <div class="col-xs-12 col-xs-offset-0 col-md-8 col-md-offset-2">
            <h1 class="h1 text-center">Sistema de Planificaci&oacute;n</h1>
            <p>
               Home...
               <?php 
               session_start();
               echo('<pre>');
               echo(print_r($_SESSION, true));
               ?>
            </p>
        </div>
    </div>
</div>