<div id="wrapper">
            <div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-sm-4">
               <?php 
                    if($_SERVER['SERVER_NAME'] == 'admin.planificacion.techo.org' || $_SERVER['SERVER_NAME'] == 'localhost')
                    {
                        $title= '<h2>Admin Planificaci&oacute;n</h2>';
                    }
                    else
                    {
                        $title = '<h2>Sistema de Planificaci&oacute;n</h2>';
                    }
                    echo($title);
                ?>
                    <ol class="breadcrumb">
                        <li>
                            <a href="/">est&aacute;s aqu&iacute;</a>
                        </li>
                        <li class="active">
                            <strong>Home</strong>
                        </li>
                    </ol>
                </div>
            </div>
            <div class="wrapper wrapper-content">
             	<div class="row">
            		<div class="col-lg-12">
             			<div class="ibox">
             				<div class="ibox-content">
                            	<div class="tabs-container">
                            		<ul id="lista1" class="nav nav-tabs">
                            			
                            		</ul>
                        		<div class="tab-content tabPai">
                        		</div>
                            	</div>
                        	</div>    
                    	</div>
                    </div>
                 </div>         
            </div>
</div>

<div id="loading-techo">
	<div class="loading"><img src="/loading.gif"></div>
</div>
<script type="text/javascript" src="/assets/js/jquery-confirm.js"></script>
<script>
	window.onload = function() {
		$('#loading-techo').show();
		var tela = document.querySelector('.tabs-container');

		//Identificar quem esta logado Pais / Sede / Regional
		var pais = <?php echo($_SESSION['Planificacion']['pais_id'])?>;
		var sede = <?php echo($_SESSION['Planificacion']['sede_id'])?>;
		var cont = 1;

		 oData    = new Object();	
		 oData.pais = pais;
		 oData.sede = sede;

		 $.ajax({
				type: "POST",
				url: "/home/userlogado",
				dataType: "json",
				data: oData,
				success: function(resp)
				{	
					//Dashboard Oficina Internacional
					if(resp['tipo'] == 'AdminValor')
					{
						resp['dash'].forEach(function(detalhe) 
						{
    						if(cont == 1)
    						{
    							//Primeira Aba
    							$("#lista1").append("<li class='active'><a data-toggle='tab' href='#tab-dash'>General</a></li>");
								$(".tabPai").append("<div id='tab-dash' class='tab-pane active'><div class='panel-body'>Conteudo General</div></div>");
								$("#lista1").append("<li class=''><a data-toggle='tab' href='#tab-"+detalhe['id']+"'>"+detalhe['dashboard']+"</a></li>");
								$(".tabPai").append("<div id='tab-"+detalhe['id']+"' class='tab-pane'><div class='panel-body'></div></div>");
								cont++;
    						}
    						else
    						{
    							$("#lista1").append("<li class=''><a data-toggle='tab' href='#tab-"+detalhe['id']+"'>"+detalhe['dashboard']+"</a></li>");
								$(".tabPai").append("<div id='tab-"+detalhe['id']+"' class='tab-pane'><div class='panel-body'></div></div>");
    						}

    						// Busca os Paises dos Dashboards
							 oDashboard     = new Object();	
							 oDashboard.id  = detalhe['id'];
							
							$.ajax({
								type: "POST",
								url: "/home/carregacompleto",
								dataType: "json",
								data: oDashboard,
								success: function(resp)
								{	
									var x = 0;
									if(resp['results'] != null)
									{
										resp['results'].forEach(function(detalhe2) 
										{
											var str = removeAccents(detalhe2['nome']);
											var str = str.replace(" ", "-");
											
											//Gera primeira parte das tab de paises
											if(x == 0)
											{
												$("#tab-"+detalhe2['id_dashboard'] +" .panel-body").append("<div class='tabs-container'><ul id='listaP"+detalhe2['id_dashboard']+"' class='nav nav-tabs'></ul><div class='tab-content filho-"+detalhe2['id_dashboard']+"'></div></div>");
												x++;
											}	
											//ABA DE PAISES
											if(detalhe['id'] == detalhe2['id_dashboard'])
											{
												//para aba 1 ativa
												if(x == 1)
												{
													$("#listaP"+detalhe2['id_dashboard']).append("<li class='active'><a data-toggle='tab' href='#tabFilho-"+detalhe2['id_pais']+"-"+detalhe['id']+"'><img src='/assets/img/flags/16/"+str+".png' alt='"+detalhe2['nome']+"'> "+detalhe2['nome']+"</a></li>");
													$(".filho-"+detalhe2['id_dashboard']).append("<div id='tabFilho-"+detalhe2['id_pais']+"-"+detalhe['id']+"' class='tab-pane active'><div class='panel-body'>"+detalhe2['select']+"</div></div>");
													x++;
												}
												else
												{
													$("#listaP"+detalhe2['id_dashboard']).append("<li class=''><a data-toggle='tab' href='#tabFilho-"+detalhe2['id_pais']+"-"+detalhe['id']+"'><img src='/assets/img/flags/16/"+str+".png' alt='"+detalhe2['nome']+"'> "+detalhe2['nome']+"</a></li>");
													$(".filho-"+detalhe2['id_dashboard']).append("<div id='tabFilho-"+detalhe2['id_pais']+"-"+detalhe['id']+"' class='tab-pane'><div class='panel-body'>"+detalhe2['select']+"</div></div>");
												}
												
											//	$(".tab-content").append("<div id='tab-pais"+detalhe['id']+"' class='tab-pane'><div class='panel-body'>Conteudos</div></div>");
											}
										});
									}
								}
							});
						});

						$("#lista1").append("<li class=''><a data-toggle='tab' id='maisDashboard' href='#tab-plus'>+ DashBoard</a></li>");
						$(".tabPai").append("<div id='tab-plus' class='tab-pane'><div class='panel-body'>Aba + Paises</div></div>");
					}

					if(resp['tipo'] == 'AdminSemValor')
					{
						$("#lista1").append("<li class='active'><a data-toggle='tab' href='#tab-dash'>General</a></li>");
						$(".tabPai").append("<div id='tab-dash' class='tab-pane active'><div class='panel-body'>Conteudo General</div></div>");
						$("#lista1").append("<li class=''><a data-toggle='tab' id='maisDashboard' href='#tab-plus'>+ DashBoard</a></li>");
						$(".tabPai").append("<div id='tab-plus' class='tab-pane'><div class='panel-body'>Aba + Paises</div></div>");
					}
					
					if(resp['tipo'] == 'Nacional' || resp['tipo'] == 'Normal')
					{
						//console.log(resp['data']);
						
						//DashBoard Sede Nacional e Outras
						resp['data'].forEach(function(details) {

							if(details['sede'])
							{
								if(cont == 1)
								{
									//Primeira Aba
									$("#lista1").append("<li class='active'><a data-toggle='tab' href='#tab-dash'>DashBoard</a></li>");
									$(".tabPai").append("<div id='tab-dash' class='tab-pane active'><div class='panel-body'>Conteudo DashBoard</div></div>");
									$("#lista1").append("<li class=''><a data-toggle='tab' href='#tab-"+cont+"'>" + details['sede'] +"</a></li>");
									$(".tabPai").append("<div id='tab-"+cont+"' class='tab-pane'><div class='panel-body'> " + details['select'] +"</div></div>");
								}
								else
								{
									$("#lista1").append("<li class=''><a data-toggle='tab' href='#tab-"+cont+"'>" + details['sede'] +"</a></li>");
									$(".tabPai").append("<div id='tab-"+cont+"' class='tab-pane'><div class='panel-body'> " + details['select'] +"</div></div>");
								}
								
								cont++;
							}
						});

						//ABA Pais para Sede Nacional e Outras Sedes
						$("#lista1").append("<li class=''><a data-toggle='tab' href='#tab-paisxx'>" + "<img src='/assets/img/flags/16/" + resp['data'][0]['nomepais'] + ".png' alt='"+resp['data'][0]['nomepais']+"'>" + ' ' +resp['data'][0]['nomepais'] +"</a></li>");

						if(resp['abapais'] == null)
						{
							resp['abapais'] = 'Ninguna Sede Planificada en ese pais!';
						}
						
						$(".tabPai").append("<div id='tab-paisxx' class='tab-pane'><div class='panel-body'>"+ resp['abapais'] +"</div></div>");
					}
					
					$('#loading-techo').hide();

					$( "#maisDashboard" ).click(function() 
					{
						oNome    = new Object();	
						var j = 0;
						 $.confirm({
                             title: 'Nuevo Dashboard',
                             content: '' +
                             '<form action="" class="formName">' +
                             '<div class="form-group">' +
                             '<label>Nombre Dashboard</label>' +
                             '<input type="text" placeholder="" class="name form-control" required />' +
                             '</div>' +
                             '</form>',
                             buttons: {
                                 formSubmit: {
                                     text: 'Grabar',
                                     btnClass: 'btn-green',
                                     action: function () {
                                         var name = this.$content.find('.name').val();
                                         if (!name) {
                                             $.alert('Nombre Obligatorio');
                                             return false;
                                         }

                                         oNome.nome = name;
										//Ajax para gravar o nome do dashboard
                                         $.ajax({
                                      		type: "POST",
                                      		url: "/home/gravadashboard",
                                      		dataType: "json",
                                      		data: oNome,
                                      		success: function(oData)
                                      		{	
                                          		//Gravou o dashboard no banco e gera abas de paises
                                      			$("#lista1").append("<li class=''><a data-toggle='tab' href='#tab-"+ j +"'>"+name+"</a></li>");
            									$(".tabPai").append("<div id='tab-"+ j +"' class='tab-pane'><div class='tabs-container'><ul class='nav nav-tabs'><li id='maispais' class='active'><a data-toggle='tab' href='#tab-1'>+ Pa&iacute;ses</a></li></ul><div class='tab-content'><div id='tab-1' class='tab-pane active'><div class='panel-body'>Haga clic en + Pa&iacute;ses para crear su lista.</div></div></div></div><div class='panel-body'>");
            									j++;
            									bindPaises();		
                                      		}
                                      	});
                                     }
                                 },
                                 cancel: function () {
                                     //close
                                 },
                             },
                             onContentReady: function () {
                                 var jc = this;
                                 this.$content.find('form').on('submit', function (e) { 
                                     e.preventDefault();
                                     jc.$$formSubmit.trigger('click'); 
                                 });
                             }
                         });
						 $( ".name" ).focus();
					});

					bindPaises();		
				}
		  });
	};
	
	function bindPaises()
	{
		$( "#maispais" ).click(function() 
		{
			$.ajax({
				type: "POST",
				url: "/home/ListaPaises",
				dataType: "json",
				success: function(resp)
				{	
					var html = '';
					var dash = '<select class="form-control" id="meudash"><option value="0">-- SELECCIONE --</option>';

					//paises
					 resp['data'].forEach(function(details) {
							html = html + "<input type='checkbox' name='"+details['id']+"' value='"+details['id']+"'>"+details['pais']+"<br>";
						}); 

						//dash
    					 resp['dash'].forEach(function(details) {
    						 	dash = dash + "<option value='"+details['id']+"'>"+details['dashboard']+"</option>";
    						}); 

    						dash = dash + '</select><br>';

    				//Monta HTML da window
					$.confirm({
		                title: 'Listado de Pa&iacute;ses',
		                content: '' +
		                '<form action="" class="formName">' +
		                '<label class="font-noraml">Elija el DashBoard</label><br>' +
		                dash +
		                '<label class="font-noraml">Elija los Paises</label><br>' +
		                '<div class="form-group">' +
		               	html +
		                '</div>' +
		                '</form>',
		                buttons: {
		                    formSubmit: {
		                        text: 'Grabar',
		                        btnClass: 'btn-green',
		                        action: function () {
		                        	oFinal           = new Object();
		                        	oFinal.dashboard = $('#meudash').val();

		                        	 $("input:checkbox:checked").each(function() {
		                        		 oFinal.paises += $(this).val() + ',';
		                        		 oFinal.paises = oFinal.paises.replace('undefined','');
		                            });

			                        //Manda pro PHP
		                        	 $.ajax({
		                        			type: "POST",
		                        			url: "/home/finaliza",
		                        			dataType: "json",
		                        			data: oFinal,
		                        			success: function(oFinal)
		                        			{	
		                        				location.reload();
		                        			}
		                        		});    
		                        }
		                    },
		                    cancel: function () {
		                        //close
		                    },
		                },
		                onContentReady: function () {
		                    var jc = this;
		                    this.$content.find('form').on('submit', function (e) { 
		                        e.preventDefault();
		                        jc.$$formSubmit.trigger('click'); 
		                    });
		                }
		            });
				}
			});
		});
	}
	
	function removeAccents(string) {
	      const accents =
	        "ÀÁÂÃÄÅàáâãäåßÒÓÔÕÕÖØòóôõöøÈÉÊËèéêëðÇçÐÌÍÎÏìíîïÙÚÛÜùúûüÑñŠšŸÿýŽž";
	      const accentsOut =
	        "AAAAAAaaaaaaBOOOOOOOooooooEEEEeeeeeCcDIIIIiiiiUUUUuuuuNnSsYyyZz";
	      return string
	        .split("")
	        .map((letter, index) => {
	          const accentIndex = accents.indexOf(letter);
	          return accentIndex !== -1 ? accentsOut[accentIndex] : letter;
	        })
	        .join("");
	    }
	</script>