<!-- 
<div class="container">
	<div class="row">
		<h1 class="h1">
			<?php $this->getPageTitle();?>
			<hr align="left" noshade="noshade" size="2" width="80%" />
		</h1>
	</div>
	 <?php foreach ($this->view->indicador as $indicador): ?>
 	<div class="row">
 		<p class="text-justify"><?php echo('Id: '. $indicador->id);?></p>
 		<p class="text-justify"><?php echo('Indicador: '. $indicador->indicador);?></p>
 		<p class="text-justify"><?php echo('A&ntilde;o: '. $indicador->ano);?></p>
 		<p class="text-justify"><?php echo('Temporalidad: '. $indicador->temporalidad);?></p>
 		<p class="text-justify"><?php echo('Tipo: '. $indicador->tipo);?></p>
 		<p class="text-justify"><?php echo('Pilar: '. $indicador->pilar);?></p>
 		<p class="text-justify"><?php echo('Area: '. $indicador->area);?></p>
 		<p class="text-justify"><?php echo('Pa&iacute;s: '. $indicador->pais);?></p>
 		<p class="text-justify"><?php echo('Sede: '. $indicador->sede);?></p>
 		<hr align="left" noshade="noshade" size="2" width="80%" />
 	</div>
 	<?php endforeach; ?>
</div>

 -->

<!DOCTYPE html>
<html>
    <head>
    	<style> html, body { margin: 0; padding: 0; height: 100%; } </style>
    </head>
	<body>
        <style>
            .ag-row-editing {
                background-color: #5bc0de !important;
            }
        </style>
        <div style="height: 100%; padding-top: 0px; box-sizing: border-box;">
            <div id="myGrid" style="height: 100%;" class="ag-theme-fresh"></div>
        </div>
		<div style="position: absolute; top: 0; left: 0;">
		</div>
    	<script src="/assets/js/jquery-1.11.1.min.js"></script>
    	<script src="/assets/js/jquery.min.js"></script>
        <script src="/assets/js/indicadores/indicadores.js" </script>
        <script src="https://unpkg.com/ag-grid-enterprise@17.0.0/dist/ag-grid-enterprise.min.js"></script></head>
	</body>
</html>

