<div class="container">
	<div class="row">
		<h1 class="h1">
			<?php $this->getPageTitle();?>
			<hr align="left" noshade="noshade" size="2" width="80%" />
		</h1>
	</div>
	 <?php foreach ($this->view->indicador as $indicador): ?>
 	<div class="row">
 		<p class="text-justify"><?php echo('Id: '. $indicador->id);?></p>
 		<p class="text-justify"><?php echo('Indicador: '. $indicador->indicador);?></p>
 		<p class="text-justify"><?php echo('A&ntilde;o: '. $indicador->ano);?></p>
 		<p class="text-justify"><?php echo('Temporalidad: '. $indicador->temporalidad);?></p>
 		<p class="text-justify"><?php echo('Tipo: '. $indicador->tipo);?></p>
 		<p class="text-justify"><?php echo('Pilar: '. $indicador->pilar);?></p>
 		<hr align="left" noshade="noshade" size="2" width="80%" />
 	</div>
 	<?php endforeach; ?>
</div>