<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-sm-4">
		<h2>Indicadores</h2>
		 <ol class="breadcrumb">
		 	<li>
                <a href="/">Home</a>
            </li>
            <li class="active">
                <strong>Indicadores</strong>
            </li>
		 </ol>
	</div>
	<div class="col-sm-8">
		<div class="title-action">
			<a href="/indicadores/add" class="btn  btn-success btn-lg carregando">Agregar Indicador</a>
		</div>
	</div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox float-e-margins">
				<div class="ibox-title">
					<h5>Listado de Indicador</h5>
				</div>
				<div class="ibox-content">
					<table class="table table-striped table-bordered table-hover dataTables-example" >
						<thead>
                    		<tr>
                                <th>Indicador</th>
                                <th>Temporalidad</th>
                                <th>Tipo</th>
                                <th>Pilar Estrat&eacute;gico</th>
                                <th>&Aacute;rea</th>
                                <th>Status</th>
                                <th>Opciones</th>
                    		</tr>
                    	</thead>
                    	<tbody>
                    	
                    	</tbody>
					</table>
					<div id="loading-techo">
                    	<div class="loading"><img src="/loading.gif"></div>
                    </div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript" src="/assets/js/jquery-confirm.js"></script>
<script>
$(document).ready(function(){
	location.href = "/indicadores";
	$('#loading-techo').show();
    $('.dataTables-example').dataTable({
   	 "language": {
         "url": "https://cdn.datatables.net/plug-ins/1.10.15/i18n/Spanish.json"
     },
        pageLength: 25,
        responsive: true,
        dom: '<"html5buttons"B>lTfgitp',
        buttons: [
            { extend: 'copy'},
            {extend: 'excel', title: 'ExampleFile'},
            {extend: 'pdf', title: 'ExampleFile'},

            {extend: 'print',
             customize: function (win){
                    $(win.document.body).addClass('white-bg');
                    $(win.document.body).css('font-size', '10px');

                    $(win.document.body).find('table')
                            .addClass('compact')
                            .css('font-size', 'inherit');
            }
            }
        ]

    });

});

function Delete(id)
{
	var id = id
    $.confirm({
        content: 'Est\u00E1 seguro de que desea borrar este indicador',
        buttons: {
            specialKey: {
                text: 'S\u00ED',
                action: function(){
                	window.location.replace("/indicadores/delete/"+id);
                }
            },
            alphabet: {
                text: 'No',
                action: function(){
                    return;
                }
            }
        }
    });
}

//Loading 
$( ".carregando" ).click(function() {
	  $('#loading-techo').css('display', 'block');
	});

</script>