 <link href="/assets/css/gestion.css" rel="stylesheet">
<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-sm-4">
		<h2>Gesti&oacute;n Anual y Tendencias</h2>
		 <ol class="breadcrumb">
		 	<li>
                <a href="/">Home</a>
            </li>
            <li class="active">
                <strong>Gesti&oacute;n y Tendencias</strong>
            </li>
		 </ol>
	</div>
	<div class="col-sm-8">
	</div>
</div>

<div class="wrapper wrapper-content animated fadeInRight custom-background">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox float-e-margins">
				<div class="col-lg-6 col-md-12 col-lg-offset-3 custom-padding-top">
                    <div class="row">
                        <div class="col-lg-6 col-md-12">
                            <a href="" class="btn btn-block custom-borda"><strong>Visual por Pilares</strong></a>
                        </div>
                        <div class="col-lg-6 col-md-12">
                            <a href="" class="btn btn-block custom-borda custom-btn-dev"><strong>Visual por Indicadores</strong></a>
                        </div>
                        <div class="col-lg-6 col-md-12">
                            <a href="" class="btn btn-block custom-borda custom-btn-dev"><strong>Visual por Focos</strong></a>
                        </div>
                        <div class="col-lg-6 col-md-12">
                            <a href="" class="btn btn-block custom-borda custom-btn-dev"><strong>Visual Sistemas de Comunidades</strong></a>
                        </div>
                        <div class=" col-lg-6 col-md-12 col-lg-offset-3">
                            <a href="" class="btn btn-block custom-borda custom-btn-dev"><strong>Tendencias</strong></a>
                        </div>
                    </div>
                </div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript" src="/assets/js/jquery-confirm.js"></script>