<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="/assets/css/tabulator.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="/assets/js/tabulator_core.js"></script>
    <script src="/assets/js/tabulator.js"></script>   
</head>
<body>
	<div class="row">
		<input type="hidden" class="form-control" id="id" value="">
		<input type="hidden" class="form-control" id="pais" value="">
		<input type="hidden" class="form-control" id="sede" value="">
		<div class="col-xs-12">
			<p><label><strong>Config. del Informe por Pilares:</strong></label><p>
		</div>
		<div class="col-xs-12 col-md-4">
			<p><label><strong>Nivel de Agrupaci&oacute;n:</strong></label></p>
			<select class="form-control" name="agrupar" id="agrupar">
    		  <option value="0">-- SELECCIONAR --</option>
              <option value="Sede">Sede</option>
              <option value="Pais">Pa&iacute;s</option>
              <option value="Region">Regi&oacute;n</option>
              <option value="Latam">Latam</option>
            </select>
		</div>
		
		<div class="col-xs-12 col-md-4">
			<p id="text-pais"><label><strong>Elija el Pa&iacute;s:</strong></label></p>
            <p id="text-region"><label><strong>Elija la Regi&oacute;n:</strong></label></p>
            <div id="tipo"></div>
            <div hidden id="regiones">
            	<select class="form-control" name="selectbox-region" id="selectbox-region">
        		  <option value="0">-- SELECCIONAR --</option>
                  <option value="cono_sur">Cono Sur Andina</option>
                  <option value="centro_america">Centroam&eacute;rica y Caribe</option>
                  <option value="centro_andina">Centro Andina Mexicana</option>
                </select>
        	</div>
		</div>
		
		<div class="col-xs-12 col-md-4">
			<div id="selectbox-sede"></div>
		</div>
	</div>
	<br>
	<button id="processar" type="button">Processar Datos</button>
	<br>
	<!-- Grid Sede -->
    <div id="table-sede"></div>
    <!-- Grid Pais -->
    <div id="table-pais"></div>
    <!-- Grid Region -->
    <div id="table-region"></div>
    <!-- Grid Latam -->
    <div id="table-latam"></div>
     <div id="loading-techo">
    	<div class="loading"><img src="/loading.gif"></div>
    </div>
</body>
<script type="text/javascript" src="/assets/js/gestion/pilares.js""></script>
</html>