<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-sm-4">
		<h2>Temporalidad</h2>
		 <ol class="breadcrumb">
		 	<li>
                <a href="/">Home</a>
            </li>
            <li class="active">
                <strong>Temporalidad</strong>
            </li>
		 </ol>
	</div>
	<div class="col-sm-8">
		<div class="title-action">
			<a href="/temporalidades/add" class="btn  btn-success btn-lg">Agregar Temporalidad</a>
		</div>
	</div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox float-e-margins">
				<div class="ibox-title">
					<h5>Listado de Temporalidad</h5>
				</div>
				<div class="ibox-content">
					<table class="table table-striped table-bordered table-hover dataTables-example" >
						<thead>
                    		<tr>
                                <th>Temporalidad</th>
                                <th>Status</th>
                                <th>Opções</th>
                    		</tr>
                    	</thead>
                    	<tbody>
                    	<?php foreach ($this->view->temporalidad as $temporalidad): ?>
                    		<tr class="gradeX">
                    		<td><?php echo($temporalidad->temporalidad);?></td>
                    		<td><?php ($temporalidad->situation == '1' ? $temporalidad->situation = 'Activo' : $temporalidad->situation = 'Inactivo'); echo($temporalidad->situation);?></td>
                    		<td class="center"><a href="/temporalidades/show/<?php echo($temporalidad->id);?>" class="btn btn-success btn-xs"><i class="fa fa-paste"></i> Editar</a><a href="/temporalidades/delete/<?php echo($temporalidad->id);?>" class="btn btn-info btn-xs"><i class="fa fa-trash"></i> Deletar</a></td>
                    	<?php endforeach; ?>
                    	</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>