<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-sm-4">
		<h2>A&ntilde;adir Foco</h2>
		<ol class="breadcrumb">
			<li>
				<a href="/">Home</a>
			</li>
			<li class="active">
				<strong>A&ntilde;adir Foco</strong>
			</li>
		</ol>
	</div>
</div>

<div class="wrapper wrapper-content">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox">
				<div class="ibox-title">
					<h5>A&ntilde;adir Foco</h5>
				</div>
				<div class="ibox-content">
					<div class="tabs-container">
						<ul class="nav nav-tabs">
							<li class="active"><a data-toggle="tab" href="#tab-1"></a></li>
						</ul>
						<div class="tab-content">
							<div id="tab-1" class="tab-pane active">
								<div class="panel-body">
									<div class="col-lg-6">
            	 						<div class="form-group">
											<label for="label">Nombre</label>
											<input type="text" class="form-control" name="nombre" id="nombre" value="<?php echo($this->view->foco->nombre);?>">
										</div>
										<div class="form-group">
											<input type="hidden" class="form-control" name="id_pais" id="pais1" value="<?php echo($this->view->foco->id_pais);?>">
											<input type="hidden" class="form-control" name="id_sede" id="sede1" value="<?php echo($this->view->foco->id_sede);?>">
										</div>
									</div>
									<div class="col-lg-6">
            	 						<div class="form-group">
											<label for="label">Descripci&oacute;n</label>
											<input type="text" class="form-control" name="descripcion" id="descripcion" value="<?php echo($this->view->foco->descripcion);?>">
										</div>
									</div>
									<div class="col-lg-6">
                                		<div class="form-group">
                                			<label for="ano">A&ntilde;o</label>
                                			<select  id="ano" class="form-control" >
                                				<option value="0">-- SELECCIONAR --</option>
                                				<?php foreach ($this->view->ano as $ano):?>
                                						<option value="<?php echo($ano->id);?>"><?php echo($ano->ano);?></option>
                                				<?php endforeach; ?>
                                			</select>
                                		</div>
                                	</div>	
                                	<div class="col-lg-3">
										<div class="form-group">
    	 									<label for="pais">Pa&iacute;s</label>
        	 								<select  id="pais" class="form-control" >
        	 									<option value="0">-- SELECCIONE --</option>
                	 							<?php foreach ($this->view->pais as $pais):?>
                	 									<option value="<?php echo($pais->id);?>"><?php echo($pais->pais);?></option>
                	 							<?php endforeach; ?>
                	 						</select>
            	 						</div>
									</div>
									<div id="loadSede">
									</div>
									<div class="col-lg-6">
            	 						<div class="form-group">
											<label for="label">Principales Obstaculos</label>
											 <div class="summernote" id="obs">
                                       		 </div>
										</div>
									</div>
									<div class="col-lg-6">
										<label for="label">Principales Hitos</label>
            	 						 <div class="summernote" id="pasos">
                                        </div>
                					</div>
									<div class="col-lg-12">
                                        <hr>
                                       <table id="example" class="display" style="width:100%">
                                            <thead>
                                                <tr>
                                                    <th></th>
                                                    <th hidden></th>
                                                    <th>Indicador</th>
                                                    <th>Temporalidad</th>
                                                    <th>Tipo</th>
                                                    <th>Pilar Estrat&eacute;gico</th>
                                                    <th>Ponderaci&oacute;n</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <?php foreach ($this->view->indicador as $indicador): ?>
                        							<tr class="">
                                            		<td></td>
                                            		<td hidden><?php echo($indicador->id);?></td>
                                            		<td><?php echo($indicador->indicador);?></td>
                                            		<td><?php echo($indicador->temporalidad);?></td>
                                            		<td><?php echo($indicador->tipo);?></td>
                                            		<td><?php echo($indicador->pilar);?></td>
                                            		<td><input type="ponderacion" name="ponderacion" onkeyup="somenteNumeros(this);"  id="<?php echo($indicador->id);?>"></td>
                                            		</tr>
                                            	<?php endforeach; ?>
                                            </tbody>
                                            <tfoot>
                                            </tfoot>
                                        </table>
                                    </div>
                                    
                                    <div class="form-group">
                            			<input type="hidden" class="form-control" id="idfoco" value="<?php echo($this->view->foco->id);?>">
                            		</div>
								</div>
							</div>
						</div>
						<div class="actions clearfix paddingTop-20">
							<button type="button" id="guardar-foco" class="btn btn-success btn-lg pull-right btn-salvar">Guardar</button>
							<a href="/foco" class="btn btn-danger btn-lg pull-right">Cancelar</a>
						</div>
					</div>
					<div id="loading-techo">
                    	<div class="loading"><img src="/loading.gif"></div>
                    </div>
				</div>
			</div>
		</div>
	</div>
</div>
<script src="/assets/js/plugins/summernote/summernote.min.js"></script>
<script type="text/javascript" src="/assets/js/foco/foco.js""></script>
<script type="text/javascript" src="/assets/js/jquery-confirm.js"></script>
<script>
 $(document).ready(function(){
	 $('#loading-techo').hide();
	  $('.summernote').summernote();
     //Indicadores
     $('#example').DataTable( {
    	 "language": {
             "url": "https://cdn.datatables.net/plug-ins/1.10.15/i18n/Spanish.json"
         },
         "info": false,
        columnDefs: [ {
            className: 'select-checkbox',
            targets:   0, 
            checkboxes: {selectRow: true}
        } ],
        select: {
            style:    'multi',
            selector: 'td:first-child'
        },
        order: [[ 1, 'asc' ]]
    } );
	
     var table = $('#example').DataTable();

     $('#example tbody').on( 'dbclick', 'tr', function () {
         $(this).toggleClass('selected');
     } );

     $("#guardar-foco").click(function() {
    	 GuardarFoco(table.rows('.selected').data());
    	});
});

 function somenteNumeros(num) {
     var er = /[^0-9.]/;
     er.lastIndex = 0;
     var campo = num;
     if (er.test(campo.value)) {
       campo.value = "";
     }
 }

</script>