<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-sm-4">
		<h2>Editar Foco</h2>
		<ol class="breadcrumb">
			<li>
				<a href="/">Home</a>
			</li>
			<li class="active">
				<strong>Editar Foco</strong>
			</li>
		</ol>
	</div>
</div>

<div class="wrapper wrapper-content">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox">
				<div class="ibox-title">
					<h5>Editar Foco</h5>
				</div>
				<div class="ibox-content">
					<div class="tabs-container">
						<ul class="nav nav-tabs">
							<li class="active"><a data-toggle="tab" href="#tab-1"></a></li>
						</ul>
						<div class="tab-content">
							<div id="tab-1" class="tab-pane active">
								<div class="panel-body">
									<div class="col-lg-6">
            	 						<div class="form-group">
											<label for="label">Nombre</label>
											<input type="text" class="form-control" name="nombre" id="nombre" value="<?php echo($this->view->foco->nombre);?>">
										</div>
										<div class="form-group">
											<input type="hidden" class="form-control" name="id_pais" id="pais1" value="<?php echo($this->view->foco->id_pais);?>">
											<input type="hidden" class="form-control" name="id_sede" id="sede1" value="<?php echo($this->view->foco->id_sede);?>">
										</div>
									</div>
									<div class="col-lg-6">
            	 						<div class="form-group">
											<label for="label">Descripci&oacute;n</label>
											<input type="text" class="form-control" name="descripcion" id="descripcion" value="<?php echo($this->view->foco->descripcion);?>">
										</div>
									</div>
									<div class="col-lg-6">
                                		<div class="form-group">
    	 									<label for="ano">A&ntilde;o</label>
        	 								<select  id="ano" class="form-control" >
                	 							<?php 
                	 							   foreach ($this->view->ano as $ano)
                                    				{
                                    				  if($this->view->foco->id_ano == $ano->id)
                                    				  {
                                    				      $ComboAno.= '<option selected value="'.$ano->id.'">'.$ano->ano.'</option>';
                                    				  }
                                    				  else
                                    				  {
                                    				      $ComboAno.= '<option value="'.$ano->id.'">'.$ano->ano.'</option>';
                                    				  }
                                    				}
                                    			?>
                                    			<?php echo($ComboAno);?>
                	 						</select>
            	 						</div>
                                	</div>	
                                	<div class="col-lg-3">
										 <div class="form-group">
    	 									<label for="pais">Pa&iacute;s</label>
        	 								<select  id="pais" class="form-control" >
        	 									<option value="0">-- SELECCIONE --</option>
                	 							<?php 
                                    				foreach ($this->view->pais as $pais)
                                    				{
                                    				    if($this->view->foco->id_pais == $pais->id)
                                    				  {
                                    				      $ComboPais.= '<option selected value="'.$pais->id.'">'.$pais->pais.'</option>';
                                    				  }
                                    				  else
                                    				  {
                                    				      $ComboPais.= '<option value="'.$pais->id.'">'.$pais->pais.'</option>';
                                    				  }
                                    				}
                                    			?>
                                    			<?php echo($ComboPais);?>
                	 						</select>
            	 						</div>
									</div>
									<div id="loadSede">
									<?php
									if($this->view->foco->id_pais != 0)
									   {
									       $html .= '<div class="col-lg-3">';
									       $html .= '<div class="form-group">';
									       $html .= '<label for="sede">Sede</label>';
									       $html .= '<select  id="sede" class="form-control" >';
									       $html .= '<option value="0">-- SELECCIONE --</option>';
									       foreach ($this->view->sede as $sede)
									       {
									           if($this->view->foco->id_sede == $sede->id)
									           {
									               $html.= '<option selected value="'.$sede->id.'">'.$sede->sede.'</option>';
									           }
									           else
									           {
									               $html.= '<option value="'.$sede->id.'">'.$sede->sede.'</option>';
									           }
									       }
									       $html .= '</select>';
									       $html .= '</div>';
									       $html .= '</div>';
									       
									       echo ($html);
									   }
									?>
									</div>
									<div class="col-lg-6">
            	 						<div class="form-group">
											<label for="label">Obs</label>
											<input type="text" class="form-control" name="obs" id="obs" value="<?php echo($this->view->foco->obs);?>">
										</div>
									</div>
									<div class="col-lg-6">
										<label for="label">Pr&oacute;ximos Pasos</label>
            	 						 <div class="summernote" id="pasos"><?php echo($this->view->foco->pasos)?>
                                        </div>
                					</div>
									<div class="col-lg-12">
                                        <hr>
                                       <table id="example" class="display" style="width:100%">
                                            <thead>
                                                <tr>
                                                    <th></th>
                                                    <th hidden></th>
                                                    <th hidden></th>
                                                    <th>Indicador</th>
                                                    <th>Temporalidad</th>
                                                    <th>Tipo</th>
                                                    <th>Pilar Estrat&eacute;gico</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <?php foreach ($this->view->todos_indicadores as $indicador): ?>
                                                	<?php foreach ($this->view->indicador_elejidos as $elejido):?>
                                                		<?php if($indicador->id == $elejido->id_indicador){?>
                                                		<tr class="selected">
                                                		<?php $selecionado = 1;?>
                                                		<?php }else{?>
                                                		<?php $selecionado = 0;?>
                            							<tr class="">
                            							<?php }?>
                            							<td></td>
                                                		<td hidden><?php echo($selecionado);?></td>
                                                		<td hidden><?php echo($indicador->id);?></td>
                                                		<td><?php echo($indicador->indicador);?></td>
                                                		<td><?php echo($indicador->temporalidad);?></td>
                                                		<td><?php echo($indicador->tipo);?></td>
                                                		<td><?php echo($indicador->pilar);?></td>
                                                		</tr>
                                                	<?php endforeach; ?>	
                                            	<?php endforeach; ?>
                                            </tbody>
                                            <tfoot>
                                            </tfoot>
                                        </table>
                                    </div>
                                    
                                    <div class="form-group">
                            			<input type="hidden" class="form-control" id="idfoco" value="<?php echo($this->view->foco->id);?>">
                            		</div>
								</div>
							</div>
						</div>
						<div class="actions clearfix paddingTop-20">
							<button type="button" id="actualizar-foco" class="btn btn-success btn-lg pull-right btn-salvar">Guardar</button>
							<a href="/foco" class="btn btn-danger btn-lg pull-right">Cancelar</a>
						</div>
					</div>
					<div id="loading-techo">
                    	<div class="loading"><img src="/loading.gif"></div>
                    </div>
				</div>
			</div>
		</div>
	</div>
</div>
<script src="/assets/js/plugins/summernote/summernote.min.js"></script>
<script type="text/javascript" src="/assets/js/foco/foco.js""></script>
<script type="text/javascript" src="/assets/js/jquery-confirm.js"></script>
<script>
 $(document).ready(function(){
	 $('#loading-techo').hide();
	 $('.summernote').summernote();
     //Indicadores
     $('#example').DataTable( {
    	 "language": {
             "url": "https://cdn.datatables.net/plug-ins/1.10.15/i18n/Spanish.json"
         },
         "info": false,
        columnDefs: [ {
            className: 'select-checkbox',
            targets:   0, 
            checkboxes: {selectRow: true}
        } ],
        select: {
            style:    'multi',
            selector: 'td:first-child'
        },
        order: [[ 1, 'desc' ]]
    } );
	
     var table = $('#example').DataTable();

     $('#example tbody').on( 'click', 'tr', function () {
         $(this).toggleClass('selected');
     } );

     $("#actualizar-foco").click(function() {
    	 ActualizarFoco(table.rows('.selected').data());
    	});
});

</script>