<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-sm-4">
		<h2>PROCESOS INTERNOS</h2>
	</div>
	<div class="col-sm-4">
		<div class="form-group">
			<label for="pais">Pa&iacute;s</label>
			<select  id="filtropais" class="form-control" >
				<option value="0">-- SELECCIONAR --</option>
				<?php foreach ($this->view->pais as $pais):?>
						<option value="<?php echo($pais['ID_Pais']);?>"><?php echo($pais['Nombre_Pais']);?></option>
				<?php endforeach; ?>
			</select>
		</div>
	</div>
	<div class="col-sm-4">
		<div class="form-group">
			<label for="pais">A&ntilde;o</label>
			<select  id="filtroano" class="form-control" >
				<option value="0">-- SELECCIONAR --</option>
				<?php foreach ($this->view->ano as $ano):?>
						<option value="<?php echo($ano->id);?>"><?php echo($ano->ano);?></option>
				<?php endforeach; ?>
			</select>
		</div>
	</div>
</div>

<div class="wrapper wrapper-content">
	<div class="row">
    	<div class="ibox">
    		<div class="col-lg-12">
    			<div class="col-lg-6">
    				<div id="load">
    					<?php foreach ($this->view->proceso as $proceso):?>
        					<div class="form-group ibox">
        						<div class="ibox-title">
        							<h5><?php echo($proceso->proceso);?></h5>&nbsp;&nbsp;&nbsp;&nbsp; - <b>Pa&iacute;s:</b> <?php echo($proceso->Pais);?> / <b>A&ntilde;o:</b> <?php echo($proceso->ano);?>
        						</div>
        						<div class="ibox-content">
            						<h3><?php echo($proceso->descripcion);?></h3>
            						<a href="#" onclick="EditarProceso(<?php echo($proceso->id);?>);"><i class="fa fa-pencil"></i> Editar &nbsp;&nbsp;&nbsp;</a><a href="#" onclick="EliminarProceso(<?php echo($proceso->id);?>);"><i class="fa fa-eraser"></i> Eliminar &nbsp;&nbsp;&nbsp;</a><a href="/proceso/relacionar/<?php echo($proceso->id);?>"><i class="fa fa-retweet"></i> Relacionar </a>
        						</div>
        					</div>	
        				<?php endforeach; ?>
    				</div>
    			</div>
    			<div id="add">
					<div class="col-lg-6">
    					<div class="ibox">
            				<div class="ibox-title">
            					<h5>A&ntilde;adir Proceso Interno</h5>
            				</div>
            				<div class="ibox-content">
    							<div id="tab-1" class="">
    								<div class="panel-body">
    									<div class="col-lg-12">
    										<div class="form-group">
    											<label for="label">Proceso</label>
    											<input type="text" class="form-control" name="proceso" id="proceso">
    										</div>
    									</div>
    									<div class="col-lg-6">
    										<div class="form-group">
                                    			<label for="pais">Pa&iacute;s</label>
                                    			<select  id="pais" class="form-control" >
                                    				<option value="0">-- GLOBAL --</option>
                                    				<?php foreach ($this->view->pais as $pais):?>
                                    						<option value="<?php echo($pais['ID_Pais']);?>"><?php echo($pais['Nombre_Pais']);?></option>
                                    				<?php endforeach; ?>
                                    			</select>
                                    		</div>
                                    	</div>	
                                    	<div class="col-lg-6">
                                    		<div class="form-group">
                                    			<label for="ano">A&ntilde;o</label>
                                    			<select  id="ano" class="form-control" >
                                    				<option value="0">-- SELECCIONAR --</option>
                                    				<?php foreach ($this->view->ano as $ano):?>
                                    						<option value="<?php echo($ano->id);?>"><?php echo($ano->ano);?></option>
                                    				<?php endforeach; ?>
                                    			</select>
                                    		</div>
                                    	</div>	
    									<div class="col-lg-12">
    										<div class="form-group">
    											<label for="label">Descripci&oacute;n</label>
    											<textarea class="form-control" id="descripcion" rows="6" cols="45"></textarea>
    										</div>
    									</div>
    									<div class="col-lg-12">
    										<button type="button" id="guardar" class="btn btn-success">Agregar</button>
    									</div>	
    								</div>
    							</div>
            				</div>
						</div>
    				</div>    			
    			</div>
    		</div>
    	</div>	
    </div>
</div>
<script type="text/javascript" src="/assets/js/jquery-confirm.js"></script>
<script type="text/javascript" src="/assets/js/proceso/proceso.js""></script>