<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-sm-4">
		<h2>Planificaci&oacute;n</h2>
		 <ol class="breadcrumb">
		 	<li>
                <a href="/">Home</a>
            </li>
            <li class="active">
                <strong>Planificaci&oacute;n</strong>
            </li>
		 </ol>
	</div>
	</div>

<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox float-e-margins">
				<div class="ibox-title">
					<h5>Listado</h5>
				</div>
				<div class="ibox-content">
					<table class="table table-striped table-bordered table-hover dataTables-example" >
						<thead>
                    		<tr>
                                <th>A&ntilde;o</th>
                                <th>Pa&iacute;s</th>
                                <th>Sede</th>
                                <th>Status</th>
                                <th>Opciones</th>
                    		</tr>
                    	</thead>
                    	<tbody>
                    	<?php foreach ($this->view->planificacion as $planificacion): ?>
                    		<tr class="gradeX">
                    		<td><?php echo($planificacion->ano);?></td>
                    		<td><?php echo($planificacion->pais);?></td>
                    		<td><?php echo($planificacion->sede);?></td>
                    		<td><?php ($planificacion->situation == '1' ? $planificacion->situation = 'Activo' : $planificacion->situation = 'Inactivo'); echo($planificacion->situation);?></td>
                    		<td class="center"><a href="/planificacion/show/<?php echo($planificacion->id);?>?pais=<?php echo($planificacion->id_pais);?>&sede=<?php echo($planificacion->id_sede);?>" class="btn btn-success btn-xs"><i class="fa fa-paste"></i> Planificar</a></td>
                    	<?php endforeach; ?>
                    	</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
$(document).ready(function(){
    $('.dataTables-example').dataTable({
   	 "language": {
         "url": "https://cdn.datatables.net/plug-ins/1.10.15/i18n/Spanish.json"
     },
        pageLength: 25,
        responsive: true,
        dom: '<"html5buttons"B>lTfgitp',
        buttons: [
            { extend: 'copy'},
            {extend: 'excel', title: 'ExampleFile'},
            {extend: 'pdf', title: 'ExampleFile'},

            {extend: 'print',
             customize: function (win){
                    $(win.document.body).addClass('white-bg');
                    $(win.document.body).css('font-size', '10px');

                    $(win.document.body).find('table')
                            .addClass('compact')
                            .css('font-size', 'inherit');
            }
            }
        ]

    });

});
</script>