<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-sm-4">
		<h2>Planificaci&oacute;n</h2>
		 <ol class="breadcrumb">
		 	<li>
                <a href="/">Home</a>
            </li>
            <li class="active">
                <strong>Planificaci&oacute;n</strong>
            </li>
		 </ol>
	</div>
	</div>

<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox float-e-margins">
				<div class="ibox-title">
					<h5>Listado</h5>
				</div>
				<div class="ibox-content">
					<table class="table table-striped table-bordered table-hover dataTables-example" >
						<thead>
                    		<tr>
                                <th>A&ntilde;o</th>
                                <th>Pa&iacute;s</th>
                                <th>Sede</th>
                                <th>Status</th>
                                <th>Opções</th>
                    		</tr>
                    	</thead>
                    	<tbody>
                    	<?php foreach ($this->view->planificacion as $planificacion): ?>
                    		<tr class="gradeX">
                    		<td><?php echo($this->view->planificacion[0]->ano);?></td>
                    		<td><?php echo($this->view->planificacion[0]->pais);?></td>
                    		<td><?php echo($this->view->planificacion[0]->sede);?></td>
                    		<td><?php ($this->view->planificacion[0]->situation == '1' ? $this->view->planificacion[0]->situation = 'Activo' : $this->view->planificacion[0]->situation = 'Inactivo'); echo($this->view->planificacion[0]->situation);?></td>
                    		<td class="center"><a href="/planificacion/show/<?php echo($this->view->planificacion[0]->id);?>" class="btn btn-success btn-xs"><i class="fa fa-paste"></i> Planificar</a><a href="/planificar/visualizar/<?php echo($this->view->planificacion[0]->id);?>" class="btn btn-info btn-xs"><i class="fa fa-eye"></i> Visualizar</a></td>
                    	<?php endforeach; ?>
                    	</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>