<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">

<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<script src="/assets/js/grid/editablegrid.js"></script>
		<!-- [DO NOT DEPLOY] --> <script src="/assets/js/grid/editablegrid_renderers.js" ></script>
		<!-- [DO NOT DEPLOY] --> <script src="/assets/js/grid/editablegrid_editors.js" ></script>
		<!-- [DO NOT DEPLOY] --> <script src="/assets/js/grid/editablegrid_validators.js" ></script>
		<!-- [DO NOT DEPLOY] --> <script src="/assets/js/grid/editablegrid_utils.js" ></script>
		<!-- [DO NOT DEPLOY] --> <script src="/assets/js/grid/editablegrid_charts.js" ></script>
		<link rel="stylesheet" href="/assets/js/grid/editablegrid.css" type="text/css" media="screen">
		<link rel="stylesheet" href="/assets/css/planificacion.css" type="text/css" media="screen">		
	</head>
	
	<body>
	<div id="filtro">
		<input type="text" id="searchField" placeholder="Buscar Indicador"/>
	</div>
	
	<div id="savando">
		<p hidden align="center" id="save1"><font color="red">Saving...</font></p>
		<p hidden align="center" id="save2"><font color="green">Save!</font></p>
	</div>
		
		<div id="tablecontent"></div>
		
		<!-- Paginator control -->
			<div id="paginator"></div>
		
		<div class="form-group">
			<input type="hidden" class="form-control" id="id" value="<?php echo($this->view->planificacion[0]->id);?>">
		</div>
		<div class="form-group">
			<input type="hidden" class="form-control" id="pais" value="<?php echo($_GET['pais']);?>">
		</div>
		<div class="form-group">
			<input type="hidden" class="form-control" id="sede" value="<?php echo($_GET['sede']);?>">
		</div>
	</body>
<script type="text/javascript" src="/assets/js/planificacion/planificacion.js""></script>
<script type="text/javascript" src="/assets/js/jquery-confirm.js"></script>

</html>
