<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">

<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<script src="/assets/js/grid/editablegrid.js"></script>
		<!-- [DO NOT DEPLOY] --> <script src="/assets/js/grid/editablegrid_renderers.js" ></script>
		<!-- [DO NOT DEPLOY] --> <script src="/assets/js/grid/editablegrid_editors.js" ></script>
		<!-- [DO NOT DEPLOY] --> <script src="/assets/js/grid/editablegrid_validators.js" ></script>
		<!-- [DO NOT DEPLOY] --> <script src="/assets/js/grid/editablegrid_utils.js" ></script>
		<!-- [DO NOT DEPLOY] --> <script src="/assets/js/grid/editablegrid_charts.js" ></script>
		<link rel="stylesheet" href="/assets/js/grid/editablegrid.css" type="text/css" media="screen">
		
		<style>
			body { font-family:'lucida grande', tahoma, verdana, arial, sans-serif; font-size:11px; white-space: nowrap}
			h1 { font-size: 10px; }
			a { color: #548dc4; text-decoration: none; }
			a:hover { text-decoration: underline; }
			table.testgrid { border-collapse: collapse; border: 1px solid #CCB; width: 800px; }
			table.testgrid td, table.testgrid th { padding: 6px; border: 1px solid #E0E0E0; }
			table.testgrid th { background: #E5E5E5; text-align: left; }
			input.invalid { background: red; color: #FDFDFD; }
		</style>
		
		<script>
			
		</script>
		
	</head>
	
	<body>
		<div id="tablecontent"></div>
		<div class="form-group">
			<input type="hidden" class="form-control" id="id" value="<?php echo($this->view->planificacion[0]->id);?>">
		</div>
	</body>
<script type="text/javascript" src="/assets/js/planificacion/planificacion.js""></script>
<script type="text/javascript" src="/assets/js/jquery-confirm.js"></script>

</html>
