<!DOCTYPE html>
<html>
<head>
    <title></title>
    <link rel="stylesheet" href="/assets/css/tabulator.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="/assets/js/tabulator_core.js"></script>
    <script src="/assets/js/tabulator.js"></script>   
</head>
<body>
	<div>
		<input type="hidden" class="form-control" id="id" value="<?php echo($this->view->planificacion[0]->id);?>">
		<input type="hidden" class="form-control" id="pais" value="<?php echo($_GET['pais']);?>">
		<input type="hidden" class="form-control" id="sede" value="<?php echo($_GET['sede']);?>">
		<label><strong>Config. Idioma:</strong></label>
		<button id="lang-german">Espa&ntilde;ol</button>
		<button id="lang-portugues">Portugu&ecirc;s</button>
		<br>
		<label><strong>Download:</strong></label>
		<button id="download-xlsx">Download Excel</button>
		<br>
		<label><strong>Ocultar / Mostrar</strong></label>
		<ul class="items">
            <li><input id="plan"  type="checkbox"> Plan</li>
            <li><input id="real"  type="checkbox"> Real</li>
            <li><input id="1"  type="checkbox"> 1 Trimestre</li>
            <li><input id="2"  type="checkbox"> 2 Trimestre</li>
            <li><input id="3"  type="checkbox"> 3 Trimestre</li>
            <li><input id="4"  type="checkbox"> 4 Trimestre</li>
            <li><input id="lista-todo" type="checkbox"> Listar Todos Indicadores</></li>
    	</ul>
		<p><label id="msg_es"><strong>Para copiar la tabla, haz click en la primera linea y pressiona las teclas CTRL + C.</strong></label></p>
		<p><label id="msg_pt" style="display: none"><strong>Para copiar a tabela, clique na primeira linha e pressione as teclas CTRL + C.</strong></label></p>
	</div>
	<br>
    <div id="example-table"></div>
    <div id="loading-techo">
    	<div class="loading"><img src="/loading.gif"></div>
    </div>
</body>
<script type="text/javascript" src="/assets/js/jquery-confirm.js"></script>
<script type="text/javascript" src="/assets/js/planificacion/planificacion_new.js""></script>
<script type="text/javascript" src="https://oss.sheetjs.com/sheetjs/xlsx.full.min.js"></script>
</html>