<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">

<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<script src="/assets/js/grid/editablegrid.js"></script>
		<!-- [DO NOT DEPLOY] --> <script src="/assets/js/grid/editablegrid_renderers.js" ></script>
		<!-- [DO NOT DEPLOY] --> <script src="/assets/js/grid/editablegrid_editors.js" ></script>
		<!-- [DO NOT DEPLOY] --> <script src="/assets/js/grid/editablegrid_validators.js" ></script>
		<!-- [DO NOT DEPLOY] --> <script src="/assets/js/grid/editablegrid_utils.js" ></script>
		<!-- [DO NOT DEPLOY] --> <script src="/assets/js/grid/editablegrid_charts.js" ></script>
		<link rel="stylesheet" href="/assets/js/grid/editablegrid.css" type="text/css" media="screen">
		
		<style>
			body { font-family:'lucida grande', tahoma, verdana, arial, sans-serif; font-size:11px; white-space: nowrap}
			h1 { font-size: 10px; }
			a { color: #548dc4; text-decoration: none; } <!-- #c46454 -->
			a:hover { text-decoration: underline; }
			table.testgrid { border-collapse: collapse; border: 1px solid #CCB; width: 800px; }
			table.testgrid td, table.testgrid th { padding: 1px; border: 1px solid #E0E0E0; }
			table.testgrid th { background: #E5E5E5; text-align: left; }
			input.invalid { background: red; color: #FDFDFD; }
#tablecontent {
 overflow-x: scroll;
    overflow-y: hidden;
    white-space: nowrap;
}
.testgrid thead tr a {
 font-size:12px;
    padding: 0 1px;
}
.editablegrid-indicador, .editablegrid-pilar, .number, .editablegrid-area {
 font-size: 13px;
    padding: 3px!important;
}
#searchField {
 margin: 9px 0px 6px 0px;
    padding: 10px;
    display: inline-block;
    width: 320px;
}
.testgrid tbody {
 max-height: 500px;
    overflow-x: scroll;
    overflow-y: hidden;
}
.testgrid tbody tr {
 background: #fff;
}
.testgrid tbody tr:hover, .testgrid tbody tr:hover .editablegrid-indicador {
 background: #f5f5f5;
}
.number.No-Edit {
    background: #dedede;
    color: #909394;
    cursor: not-allowed;
}
.editablegrid-indicador {
 width: 400px;
 position: absolute;
    background: #fff;
    margin-left: -1px;
}
.editablegrid-pilar {
 padding-left:400px!important;
}
#savando {
    position: fixed;
    right: 0;
    z-index: 2;
    padding: 20px 40px;
    top: 64px;
    margin-right: 15px;
}
#savando p {
 font-size:14px;
 color:#fff;
}
		</style>
		
		<script>
			
		</script>
		
	</head>
	
	<body>
	<div id="filtro">
		<input type="text" id="searchField" placeholder="Buscar Indicador"/>
	</div>
	
	<div id="savando">
		<p hidden align="center" id="save1"><font color="red">Saving...</font></p>
		<p hidden align="center" id="save2"><font color="green">Save!</font></p>
	</div>
		
		<div id="tablecontent"></div>
		
		<!-- Paginator control -->
			<div id="paginator"></div>
		
		<div class="form-group">
			<input type="hidden" class="form-control" id="id" value="<?php echo($this->view->planificacion[0]->id);?>">
		</div>
		<div class="form-group">
			<input type="hidden" class="form-control" id="pais" value="<?php echo($_GET['pais']);?>">
		</div>
		<div class="form-group">
			<input type="hidden" class="form-control" id="sede" value="<?php echo($_GET['sede']);?>">
		</div>
	</body>
<script type="text/javascript" src="/assets/js/planificacion/planificacion.js""></script>
<script type="text/javascript" src="/assets/js/jquery-confirm.js"></script>

</html>
