
CREATE TABLE dplanificacion (
   id INT(10) NOT NULL AUTO_INCREMENT,
   id_cplanificacion INT(10) NOT NULL COMMENT 'Id CPlanificacion',   
   id_pais INT(10) DEFAULT NULL COMMENT 'Id pais',
   id_sede INT(10) DEFAULT NULL COMMENT 'Id Sede',
   id_indicador INT(10) DEFAULT NULL COMMENT 'Id Indicador',
   enero_plan INT(10) DEFAULT NULL COMMENT 'plan Enero',
   enero_real INT(10) DEFAULT NULL COMMENT 'real Enero',
   febrero_plan INT(10) DEFAULT NULL COMMENT 'plan Febrero',
   febrero_real INT(10) DEFAULT NULL COMMENT 'real Febrero',
   marzo_plan INT(10) DEFAULT NULL COMMENT 'plan Marzo',
   marzo_real INT(10) DEFAULT NULL COMMENT 'real Marzo',
   abril_plan INT(10) DEFAULT NULL COMMENT 'plan Abril',
   abril_real INT(10) DEFAULT NULL COMMENT 'real Abril',
   mayo_plan INT(10) DEFAULT NULL COMMENT 'plan Mayo',
   mayo_real INT(10) DEFAULT NULL COMMENT 'real Mayo',
   junio_plan INT(10) DEFAULT NULL COMMENT 'plan Junio',
   junio_real INT(10) DEFAULT NULL COMMENT 'real Junio',
   julio_plan INT(10) DEFAULT NULL COMMENT 'plan Julio',
   julio_real INT(10) DEFAULT NULL COMMENT 'real Julio',
   agosto_plan INT(10) DEFAULT NULL COMMENT 'plan Agosto',
   agosto_real INT(10) DEFAULT NULL COMMENT 'real Agosto',
   septiembre_plan INT(10) DEFAULT NULL COMMENT 'plan Septiembre',
   septiembre_real INT(10) DEFAULT NULL COMMENT 'real Septiembre',
   octubre_plan INT(10) DEFAULT NULL COMMENT 'plan Octubre',
   octubre_real INT(10) DEFAULT NULL COMMENT 'real Octubre',
   noviembre_plan INT(10) DEFAULT NULL COMMENT 'plan Noviembre',
   noviembre_real INT(10) DEFAULT NULL COMMENT 'real Noviembre',
   diciembre_plan INT(10) DEFAULT NULL COMMENT 'plan Diciembre',
   diciembre_real INT(10) DEFAULT NULL COMMENT 'real Diciembre',
   id_creator INT(10) UNSIGNED NOT NULL COMMENT 'Id creator',
   id_updater INT(10) UNSIGNED NOT NULL COMMENT 'Id updater',
   date_insert DATETIME NOT NULL COMMENT 'Date insert',
   date_update DATETIME DEFAULT NULL COMMENT 'last date update',
   situation INT(1) DEFAULT 1 COMMENT 'Activo ou Inactivo',
   deleted INT(1) DEFAULT 0 COMMENT 'Deleted',
  PRIMARY KEY (id),
  FOREIGN KEY (id_cplanificacion) REFERENCES cplanificacion(id),
  FOREIGN KEY (id_indicador) REFERENCES indicador(id)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci COMMENT='Table of Detalle planificacion';