<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-sm-4">
		<h2>Informaci&oacute;n 2021</h2>
		 <ol class="breadcrumb">
		 	<li>
                <a href="/">Home</a>
            </li>
		 </ol>
	</div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
		<div class="col-lg-12">
		<iframe width="100%" height="700" src="https://datastudio.google.com/embed/reporting/0123c867-ba2c-46e1-86f7-764bac5def05/page/w4eMC" frameborder="0" style="border:0" allowfullscreen></iframe>
		</div>
	</div>
</div>