<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-sm-4">
		<h2>Infograf&iacute;a Latinoam&eacute;rica 2019</h2>
		 <ol class="breadcrumb">
		 	<li>
                <a href="/">Home</a>
            </li>
		 </ol>
	</div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
		<div class="col-lg-12">
		<iframe width="933" height="700" src="https://app.powerbi.com/view?r=eyJrIjoiMGYyZjFlNjAtNWY2YS00MjM2LWEyMjEtNTBkZjg0YWMxODZmIiwidCI6ImFhODZjY2Y3LWY5NDYtNDQ0NS04ODk5LWZhMTE1ZmJjZThlNCIsImMiOjR9" frameborder="0" allowFullScreen="true"></iframe>
		</div>
	</div>
</div>