<?php
require_once($_SERVER['DOCUMENT_ROOT'] . "/assets/Gridphp/conf.php");

date_default_timezone_set('America/Los_Angeles');
$ano = date('Y');

?>
<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-sm-4">
		<h2>Indicadores Extras</h2>
		 <ol class="breadcrumb">
		 	<li>
                <a href="/">Home</a>
            </li>
            <li class="active">
                <strong>Indicadores Extras</strong>
            </li>
		 </ol>
	</div>
	<div class="col-sm-8">
		<div class="title-action">
			<a href="/extras/add?cplanificacion=<?php echo($_GET['cplanificacion']);?>&sede=<?php echo($_GET['sede']);?>&pais=<?php echo($_GET['pais']);?>" class="btn  btn-success btn-lg">Agregar Indicadores</a>
		</div>
	</div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox float-e-margins">
				<div class="ibox-title">
				</div>
				<div class="ibox-content">
				<?php
				$pais = $_GET['pais'];
				$sede = $_GET['sede'];
				
				$dg = new C_DataGrid("SELECT * from indicador where id_pais = ". $pais . " AND addplanificacion NOT LIKE '%[".$sede."],%' AND id_sede IN (0,".$sede.") AND deleted = 0 AND situation = 1", "id", "indicadores");
                    
				$dg->set_col_hidden('id');
				$dg->set_col_hidden('id_temporalidad');
				$dg->set_col_hidden('id_tipo');
				$dg->set_col_hidden('id_pilar');
				$dg->set_col_hidden('id_pais');
				$dg->set_col_hidden('id_area');
				$dg->set_col_hidden('id_sede');
				$dg->set_col_hidden('formato');
				$dg->set_col_hidden('id_creator');
				$dg->set_col_hidden('id_updater');
				$dg->set_col_hidden('date_insert');
				$dg->set_col_hidden('date_update');
				$dg->set_col_hidden('situation');
				$dg->set_col_hidden('deleted');
				$dg->set_col_hidden('addplanificacion');
                
                // enable edit
                $dg -> enable_edit("INLINE", "Read");
                $dg -> display();
                    ?>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript" src="/assets/js/jquery-confirm.js"></script>
