<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?php $this->getPageTitle(' | ');?>Techo - Micro Framework</title>
    <link href="/assets/css/style.css" rel="stylesheet">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  </head>
  <body>
  <?php require_once __DIR__ . '/menu.phtml' ?>
  <?php $this->content(); ?>
    <script src="/assets/js/jquery.min.js"></script>
    <script src="/assets/js/bootstrap.min.js"></script>
  </body>
</html>
