<!DOCTYPE html>
<html lang="pt-br">
  	<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    	<title><?php $this->getPageTitle(' | ');?>Planificaci&oacute;n</title>
    	<script src="/assets/js/jquery-3.1.1.min.js"></script>
        <link href="/assets/css/bootstrap.min.css" rel="stylesheet">
        <link href="/assets/font-awesome/css/font-awesome.css" rel="stylesheet">
        <link href="/assets/css/animate.css" rel="stylesheet">
        <link href="/assets/css/style.css" rel="stylesheet">
    	<link href="/assets/css/plugins/chosen/bootstrap-chosen.css" rel="stylesheet">
    	<link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet">
        <link href="https://cdn.datatables.net/select/1.2.5/css/select.dataTables.min.css" rel="stylesheet">
        <link rel="stylesheet" href="/assets/css/jquery-confirm.css"/>
	</head>
  	<body>
         <?php require_once __DIR__ . '/menu.phtml' ?>
         <?php $this->content(); ?>
         <?php require_once __DIR__ . '/footer.phtml' ?>
         <script src="/assets/js/bootstrap.min.js"></script>
         <script src="/assets/js/plugins/metisMenu/jquery.metisMenu.js"></script>
         <script src="/assets/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>
         <script src="/assets/js/plugins/dataTables/datatables.min.js"></script>
         <script src="/assets/js/inspinia.js"></script>
         <script src="/assets/js/plugins/pace/pace.min.js"></script>
         <script src="/assets/js/plugins/chosen/chosen.jquery.js"></script>
         <script src="/assets/js/plugins/select2/select2.full.min.js"></script>
         <script src="https://cdn.datatables.net/select/1.2.5/js/dataTables.select.min.js"></script>
         <script>
            $("#sair").on("click", function() 
    		{
    		    window.close();
    		});

            $("#sair1").on("click", function() 
    		{
    		    window.close();
    		});
    	 </script>
	  
  	</body>
</html>
