<!DOCTYPE html>
<html lang="pt-br">
  	<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    	<title><?php $this->getPageTitle(' | ');?>Planificaci&oacute;n</title>
    	<script src="/assets/js/jquery-3.1.1.min.js"></script>
        <link href="/assets/css/bootstrap.min.css" rel="stylesheet">
        <link href="/assets/font-awesome/css/font-awesome.css" rel="stylesheet">
        <link href="/assets/css/animate.css" rel="stylesheet">
        <link href="/assets/css/plugins/summernote/summernote.css" rel="stylesheet">
    	<link href="/assets/css/plugins/summernote/summernote-bs3.css" rel="stylesheet">
        <?php 
            if($_SERVER['SERVER_NAME'] == 'admin.planificacion.techo.org' || $_SERVER['SERVER_NAME'] == 'localhost')
            {
                $css = '<link href="/assets/css/style_admin.css" rel="stylesheet">';
            }
            else
            {
                $css = '<link href="/assets/css/style.css" rel="stylesheet">';
            }
            echo($css);
        ?>
    	<link href="/assets/css/plugins/chosen/bootstrap-chosen.css" rel="stylesheet">
    	<link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet">
        <link href="https://cdn.datatables.net/select/1.2.5/css/select.dataTables.min.css" rel="stylesheet">
        <link rel="stylesheet" href="/assets/css/jquery-confirm.css"/>
        <link rel="stylesheet" href="/assets/css/bootstrap-multiselect.css"/>
	</head>
  	<body>
         <?php require_once __DIR__ . '/menu.phtml' ?>
         <?php $this->content(); ?>
         <div id="loading-techo2" style="display:none;">
        	<div class="loading"><img src="/loading.gif"></div>
        </div>
         <?php require_once __DIR__ . '/footer.phtml' ?>
         <script src="/assets/js/bootstrap.min.js"></script>
         <script src="/assets/js/plugins/metisMenu/jquery.metisMenu.js"></script>
         <script src="/assets/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>
         <script src="/assets/js/plugins/dataTables/datatables.min.js"></script>
         <script type="text/javascript" src="https://cdn.datatables.net/fixedcolumns/3.2.6/js/dataTables.fixedColumns.min.js"></script>
         <script src="/assets/js/inspinia.js"></script>
         <script src="/assets/js/plugins/pace/pace.min.js"></script>
         <script src="/assets/js/plugins/chosen/chosen.jquery.js"></script>
         <script src="/assets/js/plugins/select2/select2.full.min.js"></script>
         <script src="https://cdn.datatables.net/select/1.2.5/js/dataTables.select.min.js"></script>
         <script>
            $("#sair").on("click", function() 
    		{
    		    window.close();
    		});

            $("#sair1").on("click", function() 
    		{
    		    window.close();
    		});

            //Loading 
        	$( ".clicoucarrega" ).click(function() {
        		  $('#loading-techo2').css('display', 'block');
        		});
    		
    	 </script>
    	 
    	 <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-136104409-1"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
        
          gtag('config', 'UA-136104409-1');
        </script>
	  
  	</body>
</html>
