<nav class="navbar-default navbar-static-side" role="navigation">
	<div class="sidebar-collapse">
		<ul class="nav metismenu" id="side-menu">
			<li class="nav-header">
				<div class="dropdown profile-element"> 
					<span><img alt="image" src="/assets/img/mf-logo.png" /></span>
					<a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    	<span class="clear"> 
                    		<span class="block m-t-xs"> <strong class="font-bold"><?php session_start(); echo($_SESSION['Planificacion']['Name']);?></strong>
                    		</span>
                        </span> 
                    </a>
                </div>
                <div class="logo-element">
                	TECHO
				</div>
			</li>
			<li>
            	<a href="/"><i class="fa fa-th-large"></i> <span class="nav-label">Home</span> </a>
            </li>
            <?php 
            if($_SERVER['SERVER_NAME'] == 'admin.planificacion.techo.org')
                {
            ?>
            <li>
                <a href="#"><i class="fa fa-institution"></i> <span class="nav-label">Registros</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                	<li><a href="/anos"><i class="fa fa-plus-square-o"></i>A&ntilde;os</a></li>
                	<li><a href="/temporalidades"><i class="fa fa-plus-square-o"></i>Temporalidad</a></li>
                	<li><a href="/tipos"><i class="fa fa-plus-square-o"></i>Tipo</a></li>
                	<li><a href="/pilares"><i class="fa fa-plus-square-o"></i>Pilar</a></li>
               		<li><a href="/indicadores"><i class="fa fa-plus-square-o"></i>Indicadores</a></li>
                </ul>
            </li>
			<li>
            	<a href="/cplanificacion"><i class="fa fa-th-large"></i> <span class="nav-label">Crear Planificaci&oacute;n</span> </a>
            </li>
            <?php }?>
            <?php 
                if($_SERVER['SERVER_NAME'] == 'localhost')
                {
            ?>
            <li>
                <a href="#"><i class="fa fa-institution"></i> <span class="nav-label">Registros</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                	<li><a href="/anos"><i class="fa fa-plus-square-o"></i>A&ntilde;os</a></li>
                	<li><a href="/temporalidades"><i class="fa fa-plus-square-o"></i>Temporalidad</a></li>
                	<li><a href="/tipos"><i class="fa fa-plus-square-o"></i>Tipo</a></li>
                	<li><a href="/pilares"><i class="fa fa-plus-square-o"></i>Pilar</a></li>
               		<li><a href="/indicadores"><i class="fa fa-plus-square-o"></i>Indicadores</a></li>
                </ul>
            </li>
			<li>
            	<a href="/cplanificacion"><i class="fa fa-th-large"></i> <span class="nav-label">Crear Planificaci&oacute;n</span> </a>
            </li>
            <li>
            	<a href="/planificacion"><i class="fa fa-th-large"></i> <span class="nav-label">Planificaci&oacute;n A&ntilde;o</span> </a>
            </li>
            <li>
                <a href="/tinforme"><i class="fa fa-bar-chart"></i> <span class="nav-label">Informes por Sede</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                	<li><a href="/tinforme/mensual"><i class="fa fa-plus-square-o"></i>Mensual</a></li>
                	<li><a href="/tinforme"><i class="fa fa-plus-square-o"></i>Trimestral</a></li>
                	<li><a href="/tinforme/anual"><i class="fa fa-plus-square-o"></i>Anual</a></li>
                </ul>
            </li>
            <li>
            	<a href="/generador"><i class="fa fa-area-chart"></i> <span class="nav-label">Generador de Informes</span> </a>
            </li>
             <li>
            	<a href="/tinforme/monitoreo"><i class="fa fa-desktop"></i> <span class="nav-label">Monitoreo de KPI's por Sede</span> </a>
            </li>
            <li>
            	<a href="/tinforme/monitoreo2"><i class="fa fa-desktop"></i> <span class="nav-label">Monitoreo de KPI's por Pa&iacute;s</span> </a>
            </li>
            <li>
            	<a href="/tinforme/mproyecto"><i class="fa fa-desktop"></i> <span class="nav-label">Monitoreo de Proyectos por Pa&iacute;s</span> </a>
            </li>
            <?php }?>
            <?php 
                if($_SERVER['SERVER_NAME'] == 'planificacion.techo.org')
                {
            ?>
             <li>
                <a href="#"><i class="fa fa-institution"></i> <span class="nav-label">Registros</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
               		<li><a href="/indicadores"><i class="fa fa-plus-square-o"></i>Indicadores</a></li>
                </ul>
            </li>
            <li>
            	<a href="/planificacion"><i class="fa fa-th-large"></i> <span class="nav-label">Planificaci&oacute;n A&ntilde;o</span> </a>
            </li>
                        <li>
                <a href="/tinforme"><i class="fa fa-bar-chart"></i> <span class="nav-label">Informes por Sede</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                	<li><a href="/tinforme/mensual"><i class="fa fa-plus-square-o"></i>Mensual</a></li>
                	<li><a href="/tinforme"><i class="fa fa-plus-square-o"></i>Trimestral</a></li>
                	<li><a href="/tinforme/anual"><i class="fa fa-plus-square-o"></i>Anual</a></li>
                </ul>
            </li>
            
             <li>
            	<a href="/generador"><i class="fa fa-area-chart"></i> <span class="nav-label">Generador de Informes</span> </a>
            </li>
             <li>
            	<a href="/tinforme/monitoreo"><i class="fa fa-desktop"></i> <span class="nav-label">Monitoreo de KPI's por Sede</span> </a>
            </li>
            <li>
            	<a href="/tinforme/monitoreo2"><i class="fa fa-desktop"></i> <span class="nav-label">Monitoreo de KPI's por Pa&iacute;s</span> </a>
            </li>
            <li>
            	<a href="/tinforme/mproyecto"><i class="fa fa-desktop"></i> <span class="nav-label">Monitoreo de Proyectos por Pa&iacute;s</span> </a>
            </li>
            <?php }?>
		</ul>
	</div>
</nav>

<div id="page-wrapper" class="gray-bg">
	 <div class="row border-bottom">
	 	 <nav class="navbar navbar-static-top  " role="navigation" style="margin-bottom: 0">
	 	 	<div class="navbar-header">
            	<a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
        	</div>
        	<ul class="nav navbar-top-links navbar-right">
        		<li>
                    <span class="m-r-sm text-muted welcome-message">Bienvenido!</span>
                </li>
        	</ul>
	 	 </nav>
	  </div>
