<nav class="navbar-default navbar-static-side" role="navigation">
	<div class="sidebar-collapse">
		<ul class="nav metismenu" id="side-menu">
			<li class="nav-header">
				<div class="dropdown profile-element"> 
					<span><img alt="image" src="/assets/img/mf-logo.png" /></span>
					<a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    	<span class="clear"> <span class="block m-t-xs"> <strong class="font-bold"><?php session_start(); echo($_SESSION['Planificacion']['Name']);?></strong></span>
                        <span class="text-muted text-xs block">Admin <b class="caret"></b></span> </span> 
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a id="sair" href="#">Sair</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                	TECHO
				</div>
			</li>
			<li>
            	<a href="/"><i class="fa fa-th-large"></i> <span class="nav-label">Home</span> </a>
            </li>
            <li>
                <a href="#"><i class="fa fa-institution"></i> <span class="nav-label">Registros</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                	<li><a href="/anos"><i class="fa fa-plus-square-o"></i>A&ntilde;os</a></li>
                	<li><a href="/temporalidades"><i class="fa fa-plus-square-o"></i>Temporalidad</a></li>
                	<li><a href="/tipos"><i class="fa fa-plus-square-o"></i>Tipo</a></li>
                	<li><a href="/pilares"><i class="fa fa-plus-square-o"></i>Pilar</a></li>
               		<li><a href="/indicadores"><i class="fa fa-plus-square-o"></i>Indicadores</a></li>
                </ul>
            </li>
			<li>
            	<a href="/cplanificacion"><i class="fa fa-th-large"></i> <span class="nav-label">Crear Planificaci&oacute;n</span> </a>
            </li>
            <li>
            	<a href="/planificacion"><i class="fa fa-th-large"></i> <span class="nav-label">Planificaci&oacute;n A&ntilde;o</span> </a>
            </li>
            <li>
                <a href="/tinforme"><i class="fa fa-bar-chart"></i> <span class="nav-label">Informes</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                	<li><a href="/tinforme/mensual"><i class="fa fa-plus-square-o"></i>Mensual</a></li>
                	<li><a href="/tinforme"><i class="fa fa-plus-square-o"></i>Trimestral</a></li>
                	<li><a href="/tinforme/anual"><i class="fa fa-plus-square-o"></i>Anual</a></li>
                </ul>
            </li>
		</ul>
	</div>
</nav>

<div id="page-wrapper" class="gray-bg">
	 <div class="row border-bottom">
	 	 <nav class="navbar navbar-static-top  " role="navigation" style="margin-bottom: 0">
	 	 	<div class="navbar-header">
            	<a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
        	</div>
        	<ul class="nav navbar-top-links navbar-right">
        		<li>
                    <span class="m-r-sm text-muted welcome-message">Bienvenido!</span>
                </li>
                <li>
                    <a id="sair1" href="#">
                        <i class="fa fa-sign-out"></i> Salir
                    </a>
                </li>
        	</ul>
	 	 </nav>
	  </div>
