<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox float-e-margins">
				<div class="ibox-content">
				<div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Cuentenos su experiencia en el Sistema de Planificacion</h5>
                    </div>
                    <div class="ibox-content no-padding">

                        <div class="summernote" id="mensaje">
                            <h3>Titulo</h3>
                            Contenido...
                            <br/>
                            <br/>
                            <ul>
                                <li>Puntos de Mejora 1</li>
                                <li>Puntos de Mejora 2</li>
                                <li>Puntos de Mejora 3</li>
                            </ul>
                        </div>
                    </div>
                       <div class="mail-body text-right tooltip-demo">
                        <a class="btn btn-sm btn-primary" id="enviar" data-toggle="tooltip" data-placement="top" title="Enviar"><i class="fa fa-reply"></i> Enviar</a>
                        <a href="/" class="btn btn-white btn-sm carregando" id="sair" data-toggle="tooltip" data-placement="top"><i class="fa fa-times"></i> Cancelar</a>
                    </div>
                </div>
					 <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>Mural de Feedback</h5>
            <div class="ibox-tools">
                <span class="label label-warning-light pull-right"><?php echo(count($this->view->feedback))?> Feedback</span>
               </div>
        </div>
        <div class="ibox-content">
            <div>
               <?php foreach ($this->view->feedback as $feedback):?>
               <div class="feed-element">
                    <a href="#" class="pull-left">
                        <img alt="image" class="img-circle" src="<?php echo($feedback->foto_usuario)?>">
                    </a>
                    <div class="media-body ">
                        <small class="pull-right"><?php echo($feedback->fecha_hora)?></small>
                        <strong><?php echo($feedback->nombre_usuario)?></strong> <br>
                        <small class="text-muted"><?php echo($feedback->date_insert)?></small>
                        <div class="well">
                           <?php echo($feedback->feedback)?>
                        </div>
                    </div>
                </div>
               <?php endforeach; ?>
            </div>
        </div>
    </div>
				</div>
			</div>
		</div>
	</div>
</div>

<div id="loading-techo">
	<div class="loading"><img src="/loading.gif"></div>
</div>
                    
<script src="/assets/js/plugins/summernote/summernote.min.js"></script>
<script type="text/javascript" src="/assets/js/jquery-confirm.js"></script>

<script>
$(document).ready(function(){
	$('#loading-techo').hide();
    $('.summernote').summernote();

});
var edit = function() {
    $('.click2edit').summernote({focus: true});
};
var save = function() {
    var aHTML = $('.click2edit').code(); //save HTML If you need(aHTML: array).
    $('.click2edit').destroy();
};

//Loading 
$( "#sair" ).click(function() {
	$('#loading-techo').show();
	});

//Envia el feedback
$( "#enviar" ).click(function() {
	var markupStr = $('#mensaje').summernote('code');

	oData          = new Object();	
	oData.mensaje  = markupStr;
	
	$.ajax({
		type: "POST",
		url: "/feedback/enviar",
		dataType: "json",
		data: oData,
		success: function(oData)
		{	
			if(oData['results'])
			{
				$('#loading-techo').hide();
				$.confirm({
				    content: "Grabado con Exito.",
				    buttons: {
				        ok: function(){
				        	location.href = "/feedback";
				        }
				    }
				});
			}
			else
			{
				$('#loading-techo').hide();
				$.confirm({
				    content: "Erro ao Grabar.",
				    buttons: {
				        ok: function(){
				        	location.href = "/feedback";
				        }
				    }
				});
			}
		}
	});
	});
</script>